### ISSUE TITLE
memory leak when passing a store

### ISSUE THREAD

**Issue by Kikobeats** [jaredwray/keyv#101]
This line of code is attaching an event listener to a store passed as `store` option: https://github.com/lukechilds/keyv/blob/b87be6c60dd7ccf9efe8be3875c32c5b120fd7ff/src/index.js#L43

The thing is, a store can be shared between different keyv instances (the most common pattern there is reusing a Redis instance with difference namespace every time) so in that way the event listener is being added every time a keyv instance is created.

**Comment by szmarczak** [comment]
Why has been this closed?

**Comment by jaredwray** [comment]
@szmarczak - I believe this is now resolved

**Comment by jaredwray** [comment]
@szmarczak - pull request submitted on this. FYI

**Comment by jaredwray** [comment]
@szmarczak Keyv `v4.3.0` has been published. Closing
