### ISSUE TITLE
SSL/TLS Support for Redis Connections

### ISSUE THREAD

**Issue by 100tomer** [jaredwray/keyv#1018]
**Is your feature request related to a problem? Please describe.**
The package currently lacks support for SSL/TLS encrypted Redis connections, which is crucial for secure data transmission, especially given that Redis has supported SSL/TLS since version 6.0.

**Describe the solution you'd like**
I propose adding SSL/TLS connection support, including:
1. An enablement option for SSL/TLS.
2. Configuration for SSL/TLS parameters (CA certificate, client certificate/key).
3. Server certificate verification.
4. Guidance in the documentation on setting up secure connections.

**Comment by jaredwray** [comment]
@100tomer thanks for such a thorough feature request 🎉 

Agreed we should add SSL/TLS support. Whats your thoughts if we should wait as there is plans later this year to move to the standard redis adapter.

**Comment by 100tomer** [comment]
> @100tomer thanks for such a thorough feature request 🎉 
> 
> 
> 
> Agreed we should add SSL/TLS support. Whats your thoughts if we should wait as there is plans later this year to move to the standard redis adapter. 

I really love this package so I would love if it can be added soon. Currently it's not stopping me from continue creating in my new OpenSource platform but it soon will (when I'll publish it)

**Comment by jaredwray** [comment]
@100tomer - thanks and I think the first thing is to move to the standard redis adapter instead of ioredis. That is pretty significant work and we might be able to do this after the v5 updates and moving to ESM.

**Comment by outcomehealthcare** [comment]
upvote

**Comment by jaredwray** [comment]
@100tomer - we are starting on this work and will follow it #1119
