### ISSUE TITLE
Support for later versions of MongoDB Node.js Driver

### ISSUE THREAD

**Issue by paulrobertlloyd** [jaredwray/keyv#1028]
The MongoDB Node.js Driver is now at v6.5, however the MongoDB storage adapter for this project is currently pinned to version 4.5. 

I appreciate there may be a number of [breaking changes in version 5](https://github.com/mongodb/node-mongodb-native/blob/main/etc/notes/CHANGES_5.0.0.md) and [version 6](https://github.com/mongodb/node-mongodb-native/blob/main/etc/notes/CHANGES_6.0.0.md), but wondered if there were any plans to support these versions of the official driver at all?

**Comment by jaredwray** [comment]
@paulrobertlloyd - thanks for calling this out. We are right now working on v5 with the core library and most likely will look at upgrading the main mongo package after that. Will keep this open.

**Comment by jaredwray** [comment]
@paulrobertlloyd - this has been updated on the following pull request: https://github.com/jaredwray/keyv/pull/1056

We will release this with Keyv v5 rc1 later this week.

**Comment by paulrobertlloyd** [comment]
Oh, very cool. I shall look forward to trying out the RC!
