### ISSUE TITLE
Get rid of json-buffer

### ISSUE THREAD

**Issue by drodil** [jaredwray/keyv#1029]
**Is your feature request related to a problem? Please describe.**
The `json-buffer` project was already been archived many years ago (https://github.com/dominictarr/json-buffer) and the functionality is not even very hard to replace with a better solution. For example, the parse method is incredibly slow due to it using regex for everything (https://github.com/dominictarr/json-buffer/blob/master/index.js#L51). 

**Describe the solution you'd like**

Having own solution would make maintenance easier and also get rid of archived dependency.

**Comment by jaredwray** [comment]
@drodil - love the idea. Are there any solutions already available?

**Comment by drodil** [comment]
I would start by just copying the current json-buffer implementation to this and remove the regex stuff as it costs in perf.

**Comment by gperdomor** [comment]
@drodil I just notice that in this issue https://github.com/jaredwray/keyv/issues/252 there is a mention to json-buffer too... Says `Use https://www.npmjs.com/package/buffer over using json-buffer which relies on Node'sBuffer`... maybe you can take a look 😄
