### ISSUE TITLE
Namespace will be missed using KeyvMongo

### ISSUE THREAD

**Issue by yb** [jaredwray/keyv#1041]
**Describe the bug**
I found that if I use `new KeyvMongo()` directly, it will miss the namespace configuration in the options.

**How To Reproduce (best to provide workable code or tests!)**
```
import KeyvMongo from '@keyv/mongo'

new KeyvMongo(process.env['MONGODB_URL'], { namespace: 'some' })
```
as configured above, but in mongodb the key field does not start with `some:`

The reason why `new Keyv(<mongodb>)` is not used is because `@keyv/mongo` will not be packaged when building the `next.js` with standalone mode, so I referred to the solution of [@lukechilds ](https://github.com/jaredwray/keyv/issues/70#issuecomment-451598693) in #70 

**Versions:**
@keyv/mongo v2.2.8
keyv 4.5.4

**Comment by yb** [comment]
I referred to [@matzkoh](https://github.com/jaredwray/keyv/issues/70#issuecomment-1349512010)'s answer and solved the problem of next.js standalone deployment:
```
import Keyv from 'keyv'
import '@keyv/mongo'

new Keyv(process.env['MONGODB_URL'], { namespace: 'some' })
```

However, if `@keyv/mongo` is not recommended to be used directly, please close this issue.

**Comment by jaredwray** [comment]
@yb  thanks for submitting this and yes Keyv Mongo is not supposed to be used without the main Keyv module.
