### ISSUE TITLE
Support for setting multiples keys

### ISSUE THREAD

**Issue by gperdomor** [jaredwray/keyv#1042]
**Is your feature request related to a problem? Please describe.**
Currently Keyv expose methods for getting multiple keys using the get method and passing an array of keys as argument, sadly this is not possible in `set` method...

**Describe the solution you'd like**
Expose a multi set keys method in Keyv :D

**Comment by jaredwray** [comment]
@gperdomor - thanks so much and I am going to look at this in the future (next 90 days). If it gets a ton of upvotes we will consider it.

**Comment by jaredwray** [comment]
@gperdomor - I havent seen anybody asking for this so going to close it down and look at this in the future.

**Comment by gperdomor** [comment]
@jaredwray I think is a mistake close this, because will prevent users to migrate from cache-manager to keyv 😢
