### ISSUE TITLE
When creating multiple instances of Keyv with postgres adapter, table creation fails and keyv not working

### ISSUE THREAD

**Issue by ilia-shakalov** [jaredwray/keyv#1066]
Foremost, thanks to all contributors to this project! Your efforts have made it incredibly helpful, and I truly appreciate it!

**Describe the bug**
When creating multiple instances of Keyv with postgres adapter, table creation fails and keyv not working

**How To Reproduce (best to provide workable code or tests!)**
Prepare postgres database without keyv table created. Then try to you define multiple instance (to use different namespaces) of keyv using postgresql adapter, for example:

```typescript
const keyvA = new Keyv(connectionString, {
    namespace: 'namespace-a',
    adapter: 'postgresql',
});
const keyvB = new Keyv(connectionString, {
    namespace: 'namespace-b',
    adapter: 'postgresql',
});
```

Then, when you try to run this code, you will get two errors:

```
stack: error: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
    at .../node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async .../node_modules/@keyv/postgres/src/index.ts:32:18
    at async .../node_modules/@keyv/postgres/src/index.ts:52:5
```

If you try to use these keyv after that, you get an error

```
TypeError
   stack: TypeError: query is not a function
    at .../node_modules/@keyv/postgres/src/index.ts:58:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I believe that happens because of connection that takes place inside the constructor https://github.com/jaredwray/keyv/blob/4eedac9bde7c9253aa4dd882b16dd36be8eb5e95/packages/postgres/src/index.ts#L44. I didn't find any workaround other than create keyv table manually once before starting the app.

I spotted that changes made in https://github.com/jaredwray/keyv/commit/364b3fc9b1b1c3a679d5bedfe799a821c8586a4c kinda fixes the issue and with that fix the `query is not a function` is no longer appear. But it seems like the root issue is that connection and creation of tables happens inside constructor and client doesn't have any control over it.

Perhaps, it may be worth to consider splitting construction and initiation process in two separate steps, like
- We create some instance of PSQL adapter, with async init method, which connects & creates schemas/tables/etc. Users of the library can control that this is a single instance of adapter and have control over the initiation
- Then this instance is passed to Keyv constructor, and it can be used the same way as it does it now.

I am happy to contribute to fix the issue, but I would like to know your opinion on the problem and the suggested solution. Thanks!

**Comment by jaredwray** [comment]
@ilia-shakalov - thanks and I am looking at this now.

**Comment by jaredwray** [comment]
@ilia-shakalov - I made a new test and validated that it does work with two name spaces. One thing I would suggest is to run initiate the store outside and then bind it to the `Keyv` class. Here is an example:

```typescript
test.it('create two instances and make sure they do not conflict', async t => {
	const postgresUri = 'postgresql://postgres:postgres@localhost:5432/keyv_test';
	const postgresA = new KeyvPostgres({uri: postgresUri});
	const postgresB = new KeyvPostgres({uri: postgresUri});
	const keyvA = new Keyv({
		store: postgresA,
		namespace: 'namespace-a',
	});
	const keyvB = new Keyv({
		store: postgresB,
		namespace: 'namespace-b',
	});

	t.expect(await keyvA.set('foo', 'bar')).toBe(true);
	t.expect(await keyvA.get('foo')).toBe('bar');
	t.expect(await keyvB.set('foo', 'baz')).toBe(true);
	t.expect(await keyvB.get('foo')).toBe('baz');
});
```

Here is the referenced test: https://github.com/jaredwray/keyv/blob/0747de465fbd8692ba02bffc359e2e943ce76444/packages/postgres/test/test.ts#L62

Hope this helps!
