### ISSUE TITLE
TypeError: Class extends value [object Object] is not a constructor or null when using keyv in nextjs 14 app

### ISSUE THREAD

**Issue by yaman3bd** [jaredwray/keyv#1079]
**Describe the bug**
I want to use `keyv` in my nextjs middleware to store/access some values from my app cache, I have set everything up
as it was explained here: https://github.com/jaredwray/keyv/issues/1065
it is working fine for all my server pages, except it throws an error when I import `keyv` in the middleware. 
the error only shows when I import `keyv` in the middleware or in a file I import it to use it in my middleware for example, import `keyv` in a helper file and import any helper func in the middleware it shows the same error
the error:
![Screenshot 2024-06-27 at 10 49 34 PM](https://github.com/jaredwray/keyv/assets/58285821/25ff85ad-9975-45e4-9317-35ab2fd37bed)

my deps:
```json
"dependencies": {
    "@keyv/sqlite": "^3.6.7",
    "keyv": "^4.5.4",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18"
  },
```

**How To Reproduce (best to provide workable code or tests!)**
https://github.com/yaman3bd/keyv-nextjs-issue

1. clone the repo
2. npm install
3. npm run dev

open the project and it will throw the error

**Comment by jaredwray** [comment]
@yaman3bd what version of nodejs are you using?

**Comment by yaman3bd** [comment]
node: `v20.10.0`. 
npm: `8.19.1`.

**Comment by yaman3bd** [comment]
@jaredwray 
I think this issue happens because the runtime that the middleware is using is edge runtime, not a nodejs
I had a workaround for this:
moved `keyv` into an API route and called the API route from middleware using `fetch()`.
but I do not like this approach it adds an extra roundtrip.

**Comment by jaredwray** [comment]
@yaman3bd  - I haven't heard of this edge runtime. Are there docs on it anywhere?

Either way I dont know if that will be supported. One thing to try out is `v5` as it might have many of the fixes you need. You can do that by doing `npm install keyv@next`
