### ISSUE TITLE
[QUESTION]: serialize/deserialize 

### ISSUE THREAD

**Issue by simplecommerce** [jaredwray/keyv#1081]
Hi,

This is just a simple question, I was wondering what is the direct impact of not using the serialize/deserialize methods?

If I do the following:

```
serialize: data => data,
deserialize: data => data,
```

Am I going to have any issues?

Thanks!

**Comment by simplecommerce** [comment]
I also noticed that I cannot seem to use `EJSON.deserialize` from `bson` package.
Because the `EJSON.serialize` doesn't convert it to a string, and there is a string check to call the custom `deserialize` function.
I assume its built this way because it expects a string.

**Comment by jaredwray** [comment]
@simplecommerce the major thing this is used for is serializing the json to a compatible format for all the different data stores and then deserializing it. If you know the data store and are confident you can overwrite these items. Here is a reference on how do do this: https://github.com/jaredwray/keyv/blob/main/packages/keyv/README.md#custom-serializers
