### ISSUE TITLE
Missing LICENSE file in npm package

### ISSUE THREAD

**Issue by datcat17** [jaredwray/keyv#1082]
**Describe the bug**
There is no license file included with the npm package, possibly making it illegal (not a lawyer) for it to be distributed that way. It also makes it harder for license checking tools to generate license disclaimers with the full license text. There is a copyright statement at the bottom of the README, but that legally (again, not a lawyer) isn't enough for distribution under the MIT license.

**How To Reproduce (best to provide workable code or tests!)**
Install the npm package in any project and look at the corresponding folder in the node_modules folder. Alternatively, look at the code on npmjs.

_PS: Not sure if this is technically a bug or not_

**Comment by jaredwray** [comment]
@datcat17 we usually show it on the mono repo but makes sense to include it on the distribution. Not a big issue as it is under MIT.

These will be published on our next release in the next 30 days.
