### ISSUE TITLE
The disconnect is not implemented for mongodb adapter.

### ISSUE THREAD

**Issue by tatejones** [jaredwray/keyv#1084]
**Describe the bug**
There is no way to close connections for a graceful shutdown of the keyv mongodb adapter.

**How To Reproduce (best to provide workable code or tests!)**
1. Using MongoDb as keyv adaptor with disconnect called on exit interrupt
2. terminal signal is sent to exit the node js process with a keyv mongodb running
3. node js doesn't exit.
4. installed wtfnode npm 
5. performed a dump to confirm sockets to 27017 are open.

**Comment by jaredwray** [comment]
@tatejones - Hi. That is correct that mongo does not have this feature. Happy to take a pull request on this or I will leave it to see if others want to upvote this with a 👍

**Comment by tatejones** [comment]
A pull request has been issued.  The MongodbClient needed to be exposed on the KeyvMongoConnect type to allow the disconnect to method to access the close() method.

**Comment by jaredwray** [comment]
Thanks for the pull request. This has been merged and should be released in the next couple weeks.
