### ISSUE TITLE
Mongodb adaptor using factory results in different serialisation.

### ISSUE THREAD

**Issue by tatejones** [jaredwray/keyv#1086]
**Describe the bug**

The serialisation of an object is different depending on how the keyv api is constructed.

**How To Reproduce (best to provide workable code or tests!)**

```
test.it.only('Serialise object using direct store implementation', async t => {
	const keyv = new KeyvMongo(mongoURL, {collection: 'bar1'});
	await keyv.set('foo', {
		_string: 'baz', _number: 1, _boolean: true, _null: null, _array: [1, 2, 3], _object: {name: 'fred'}, _date: new Date('2021-01-01T00:00:00.000Z'),
	});
	const result = await keyv.get('foo');
	t.expect(result).toEqual({
		_string: 'baz', _number: 1, _boolean: true, _null: null, _array: [1, 2, 3], _object: {name: 'fred'}, _date: new Date('2021-01-01T00:00:00.000Z'),
	});
	await keyv.disconnect();
});
```
The "value" stored in the document is an object.  Which I assume is the correct behaviour.  

```
test.it.only('Serialise object using factory', async t => {
	const mongoDatabase = new KeyvMongo(mongoURL, {collection: 'bar2'});
	const keyv = new Keyv(mongoDatabase);
	await keyv.set('foo', {
		_string: 'baz', _number: 1, _boolean: true, _null: null, _array: [1, 2, 3], _object: {name: 'fred'}, _date: new Date('2021-01-01T00:00:00.000Z'),
	});
	const result = await keyv.get('foo');
	t.expect(result).toEqual({
		_string: 'baz', _number: 1, _boolean: true, _null: null, _array: [1, 2, 3], _object: {name: 'fred'}, _date: new Date('2021-01-01T00:00:00.000Z'),
	});
	await keyv.disconnect();
});
```
This fails and the "value" stored in mongodb is a "string" and not a document.

**Comment by tatejones** [comment]
Letting MongoDb perform the serialize and deserialize seems to have the desired outcome, except it does nest the document under value again with an expires property.   

The keyv default serialization assumes the storage mechanism cannot handle dynamic schemas like MongoDb.  The result is:
The value has been
1.  Mutated with the loss of data types (eg. dates).  The set and get are not equal.
2. Serialized/Deserialized twice. Once by the keyv default implementation and by mongodb (bson).  A huge performance hit.
3. Store as a string.  Storing as bson is much more efficient than a plain string.  Less space 
4. Difficult to inspect and query.   Support better access with queries and indexes.

Question:  Should the adapter be able to provide or override the default serialization implementation provided by the keyv?  

```
test.it('Serialise object using factory implementation', async t => {
	const mongoDatabaseAdapter = new KeyvMongo(mongoURL, {collection: 'bar2'});
	const keyv = new Keyv(mongoDatabaseAdapter, {
		serialize: (data: any) => data,
		deserialize: (data: any) => data,
	});
	await keyv.set('foo', {
		_string: 'baz', _number: 1, _boolean: true, _null: null, _array: [1, 2, 3], _object: {name: 'fred'}, _date: new Date('2021-01-01T00:00:00.000Z'),
	});
	const result = await keyv.get('foo');
	t.expect(result).toEqual({
		_string: 'baz', _number: 1, _boolean: true, _null: null, _array: [1, 2, 3], _object: {name: 'fred'}, _date: new Date('2021-01-01T00:00:00.000Z'),
	});
	await keyv.disconnect();
});
```

```
{
    "_id" : "66970662777985f58c45e9f9",
    "key" : "keyv:foo",
    "expiresAt" : null,
    "value" : {
        "value" : {
            "_string" : "baz",
            "_number" : 1,
            "_boolean" : true,
            "_null" : null,
            "_array" : [
                1,
                2,
                3
            ],
            "_object" : {
                "name" : "fred"
            },
            "_date" : "2021-01-01T10:00:00.000+1000"
        },
        "expires" : null
    }
}
```

Note:  The value has been automatically parsed to BJSON with correct types. 

![image](https://github.com/user-attachments/assets/a77ac60b-78a5-45fd-b38b-11a40252c8d4)

**Comment by jaredwray** [comment]
@tatejones - I dont know if it would be wise to do it at the mongo level. One thing you can do is to set the serialize and deserialize at Keyv module. Going to close this out as this would be a good work around. 

https://github.com/jaredwray/keyv/blob/main/packages/keyv/README.md#custom-serializers

**Comment by tatejones** [comment]
That is what my code sample does.  Why isn’t this the default  behaviour for this adapter?  At the moment all the unit tests at the MongoDB level assume this, but when using the keyv factory it defaults to string serialisation.  At least this inconsistency should be documented as the default behaviour of the keyv changes the contents.  Eg.  Object to string vs object to object
