### ISSUE TITLE
Gzip compression does not work when configured in Keyv `compression` object

### ISSUE THREAD

**Issue by HelaGone** [jaredwray/keyv#1107]
**Describe the bug**
I have an ApolloServer V4 running with a Redis instance as an external Cache. Everything is working fine except when I try to enable gzip compression. As the documentation states it should be as easy as passing the new KeyvGzip() class to the compression field in the Keyv class. However It's not and whenever a request is made it throws an error saying that the compression method is unknown. 
```
import Keyv from 'keyv';
import KeyvGzip from '@keyv/compress-gzip';
const keyv = new Keyv({store: new Map(), compression: new KeyvGzip()});

```

Here is my current basic configuration:
```
const isProduction = envConfig.ENV_NAME === "production";
const schema = makeExecutableSchema({ typeDefs, resolvers });
const shouldUseRedis = !!envConfig.REDIS_HOST;
// REDIS CONF
const REDIS_CONNECTION_STRING = `redis://default:${
  envConfig.REDIS_PASSWORD
}@${envConfig.REDIS_HOST}:${envConfig.REDIS_PORT ?? 6379}`;

if(shouldUseRedis) console.log("Setting up redis 💾 for cache");
const redis = new KeyvRedis(REDIS_CONNECTION_STRING);
const keyv = new Keyv({store: redis, compression: new KeyvGzip()});
const redisCache = new KeyvAdapter(keyv);
const apolloServer = new ApolloServer({
  schema,
  introspection: true,
  status400ForVariableCoercionErrors: true,
  cache: shouldUseRedis ? redisCache : undefined,
  plugins: isProduction ? [ApolloServerPluginLandingPageDisabled()] : []
});

// THIS FUNCTION STARTS THE APOLLO SERVER
async function startServer(){
  const {url} = await startStandaloneServer(apolloServer, {
    context: async () => {
      return{
        dataSources: dataSources(shouldUseRedis ? redisCache: undefined)
      }
    },
    listen: {port: 4000}
  });
  console.log(`Server ready at ${url}`);
}
// ACCTUALLY START THE APOLLO SERVER
startServer();
```

**Comment by jaredwray** [comment]
@HelaGone - can you send me the versions so I can try to recreate this? What happens if you do not use the compression?

**Comment by HelaGone** [comment]
sure thing. 
This is the list of packages I'm using:
<img width="390" alt="Screenshot 2024-08-05 at 17 00 48" src="https://github.com/user-attachments/assets/59c1c337-6f9d-4d78-a8f8-0d47b3f4569e">

**Comment by jaredwray** [comment]
@HelaGone - thanks. I am not seeing @keyv/compress-gzip in the list. Are we missing it?

**Comment by HelaGone** [comment]
Oh my mistake. I was testing something else. I have updated the previous comment
`@keyv/compress-gzip@1.2.3` is the package version I was trying with. 
Answering your previous question, if I don't use any compression the data is stored in Redis as a "stringified" json (JSON.stringify)

**Comment by jaredwray** [comment]
This should work but I haven't tested with apollo server but the core library itself is validated with this unit test in Keyv:

```js
test.it('compress/decompress with gzip', async t => {
	// @ts-expect-error - compression options
	const keyv = new Keyv({store: new Map(), compression: new KeyvGzip()});
	await keyv.set('foo', 'bar');
	t.expect(await keyv.get('foo')).toBe('bar');
});
```

https://github.com/jaredwray/keyv/blob/d2855f846fab321f00ebec3edd7a1937e5aadd47/packages/keyv/test/test.ts#L350

**Comment by djedje72** [comment]
Hello @jaredwray , if you don't set any value before getting value, an error occurs when using compression :

```ts
test.it('decompress should not throw error when empty with gzip', async t => {
	const keyv = new Keyv({store: new Map(), compression: new KeyvGzip()});
	await t.expect(keyv.get('foo')).rejects.not.toThrowError();
});
```

![image](https://github.com/user-attachments/assets/460a977f-4dce-4190-b201-ec56145ac98c)
