### ISSUE TITLE
V5.0.0 Bug in the example code for hooks in keyv/packages/keyv /README.md

### ISSUE THREAD

**Issue by MarvinBo** [jaredwray/keyv#1114]
In the readme for keyv (keyv/packages/keyv /README.md) three examples are given for using hooks, e.g.:

keyv.hooks.**_addListener_**(KeyvHooks.PRE_SET, (key, value) => console.log(`Setting key ${key} to ${value}`));

This hook is never executed. "addHandler" should be used instead:

keyv.hooks.**_addHandler_**(KeyvHooks.PRE_SET, (key, value) => console.log(`Setting key ${key} to ${value}`));

**Comment by jaredwray** [comment]
@MarvinBo - thanks for finding this 🎉 

we will get it updated today!
