### ISSUE TITLE
@keyv/postgres doesn't work with ESM

### ISSUE THREAD

**Issue by meotimdihia** [jaredwray/keyv#1137]
**Describe the bug**
import { Pool } from "pg";
         ^^^^
SyntaxError: The requested module 'pg' does not provide an export named 'Pool'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

**How To Reproduce (best to provide workable code or tests!)**
```Typescript
import Keyv from "keyv"
import KeyvPostgres from "@keyv/postgres"

const keyv = new Keyv(new KeyvPostgres(process.env.DATABASE_URL))
export default keyv
```

This problem was told in this issue: https://github.com/brianc/node-postgres/issues/3060#issuecomment-1748047884
We could fix it in this file: https://github.com/jaredwray/keyv/blob/main/packages/postgres/src/pool.ts#L1

**Comment by jaredwray** [comment]
@meotimdihia - thanks for the info on this. I am looking at this now and will test to see if there is an easy fix on this.

**Comment by jaredwray** [comment]
PR Request is in and should be published in the next hour with the change: #1138

**Comment by jaredwray** [comment]
@meotimdihia - version `2.0.3` is now live. Hope that works.

**Comment by meotimdihia** [comment]
thanks, it works now :)

**Comment by sharpprahs** [comment]
same problem.. right now just use // @ts-ignore and this worked, I'll get back to this problem later.
`// backend/src/db/connections/connection_main.ts
// @ts-ignore
import pg from 'pg';
const { Pool } = pg;
import { drizzle } from 'drizzle-orm/node-postgres';
import * as dotenv from 'dotenv';

// Load environment variables from .env
dotenv.config();

// Create a new Pool instance
const pool = new Pool({
    connectionString: process.env.DATABASE_URL, // Ensure this is correct
});

// Use the drizzle library with the pg Pool
export const db = drizzle(pool);`
