### ISSUE TITLE
Add default values

### ISSUE THREAD

**Issue by julian-weinert** [jaredwray/keyv#118]
As you might have guessed, this is not an issue, but a feature request.
I'd like to have the possibility to add default values for keys.

When creating an instance it would check the options-provided key / value pairs and if the key is not present save the value accordingly.

**Comment by jaredwray** [comment]
@julian-weinert - closing this out. Let me know if you still need help on this.

**Comment by julian-weinert** [comment]
Hello @jaredwray sorry for not being able to respond immediately within 4 days, I usually have a lot of things going and am not hanging around GitHub every day.
Also after more than a year without any reaction I didn't think about this anymore at all.

I'm not sure how to provide more detail than "default values". How it would work or be implemented in detail wouldn't really matter to me. Only thing is having default values.
Default as in a value that gets returned when no custom value was stored.

A code example?

```JavaScript
const keyv = new Keyv('mysql://user:pass@localhost:3306/dbname', {
    key1: "default_value_1",
    key2: 42
});

// or
keyv.setDefaultValues({
    key1: "default_value_1",
    key2: 42
});
```

Hope that helps.

**Comment by jaredwray** [comment]
@julian-weinert - no worries at all. I think for right now this is not on roadmap to do default values in `keyv` as it is pretty easy to just have code that is wrapped around that handles this scenario.
