### ISSUE TITLE
Docs and types issue for @keyv/valkey

### ISSUE THREAD

**Issue by nicokaiser** [jaredwray/keyv#1203]
Two minor documentation / type issues:

- In the README of the valkey package, `@keyv/redis` is metioned multiple times. I guess this should be `@keyv/valkey`?

- In the types.ts of `@keyv/valkey`, it is not specified that an existing Redis/ioredis instance can be used:

```js
import KeyvValkey from '@keyv/valkey'; // must be '@keyv/valkey' instead of '@keyv/redis'
import Redis from 'ioredis';

const redis = new Redis.Redis('redis://user:pass@localhost:6379'); // must be 'Redis.Redis' instead of 'Redis'
const store = new KeyvValkey(redis); // does work, but TypeScript throws an error because types.ts is not correct about this
```

**Comment by jaredwray** [comment]
fixing the readme

**Comment by jaredwray** [comment]
I think the fix on the redis adapter is this:

```js
import KeyvValkey from '@keyv/valkey'; 
import Redis from 'iovalkey';

const redis = new Redis('redis://user:pass@localhost:6379'); 
const store = new KeyvValkey(redis);
```
Check out this test as it is working:
https://github.com/jaredwray/keyv/blob/bb7bf89aa67898a2aae32c640e2a79142fa015a4/packages/valkey/test/test.ts#L18
