### ISSUE TITLE
Documentation mismatch for @keyv/valkey: useSets vs useRedisSets

### ISSUE THREAD

**Issue by nicokaiser** [jaredwray/keyv#1204]
In the (yet unreleased!) main branch of the repository, the `useRedisSets` configuration option seems to have been renamed to `useSets`. This is reflected in the official documentation on https://keyv.org/docs/storage-adapters/valkey/

However `useSets` is not working in the released (1.0.0) version. The version on npm requires `useRedisSets`.

Either release a `2.0.0` version (semver-major because of breaking change), or revert (docs or package) to `useRedisSets` because this can lead to unwanted behaviour.

**Comment by jaredwray** [comment]
@nicokaiser - thanks for finding this and I am going to get it back to `useRedisSets`

**Comment by jaredwray** [comment]
https://github.com/jaredwray/keyv/pull/1205
