### ISSUE TITLE
Allow custom namespace prefixing when `useRedisSets` is disabled

### ISSUE THREAD

**Issue by johannbrynjar** [jaredwray/keyv#1221]
**Is your feature request related to a problem? Please describe.**
Currently, when `useRedisSets` is set to `false`, the library automatically adds a default prefix (``sets:namespace:*`) to the namespace.

https://github.com/jaredwray/keyv/blob/4e59d1c5cd65b505b9a38dc7b20e6c8a4f7b9264/packages/valkey/src/index.ts#L43

This behavior can be restrictive for developers who want more flexibility in managing their namespaces. Is there a specific reason for enforcing this prefix?

Or is it some legasl reason why it add this prefix?

**Describe the solution you'd like**
I propose removing the default prefix for namespaces when `useRedisSets` is disabled. Instead, allow consumers/programmers to define their own prefixing strategy for namespaces. This approach would provide greater control and customization for library users.

**Comment by jaredwray** [comment]
@johannbrynjar - we have plans to do a big overhaul to valkey using iovalkey in 2025 with the following changes:

- `removing useRedisSets` this has caused more issues than anything and in the new `@keyv/redis` package we removed it completely. 
- `Better Namespace Support` - We are now adding better namespace support and you can see it on the new `@keyv/redis` driver as an example. 

This will be a breaking change but do plan to get to this in the first 2-3 months of 2025. You can see what we have done here with the latest redis version: https://github.com/jaredwray/keyv/tree/main/packages/redis

I will close this out until we get started on this feature and will create a new issue with the upgrade and tag you in it.
