### ISSUE TITLE
KeyvRedis is not a constructor & Keyv is not a constructor

### ISSUE THREAD

**Issue by X-Newbie** [jaredwray/keyv#1224]
**Describe the bug**
I get an error when trying to use cjm imports. I am using the latest version of keyv and @keyv/redis. With esm import i don't have this error.

**How To Reproduce (best to provide workable code or tests!)**
```
const Keyv = require("keyv");
const KeyvRedis = require("@keyv/redis");

const keyv = new Keyv(new KeyvRedis("redis://:pass@localhost:6379"))


keyv.set('asd', 'asd')
```

**Comment by jaredwray** [comment]
@X-Newbie - Hi! I think you will want to do the default property to make this work with CommonJS such as:

```js
const Keyv = require("keyv").default;
const KeyvRedis = require("@keyv/redis").default;

const keyv = new Keyv(new KeyvRedis("redis://:pass@localhost:6379"))


keyv.set('asd', 'asd')
```

One note on CJS support. We try our best to keep backwards compatibility but sometimes the modules themselves do not support it and that will cause the issue. If that is the case I would suggest to stay with v4.x.x of Keyv and an older version of the module that supports it.
