### ISSUE TITLE
keyv.iterator is not a function when using KeyvEtcd

### ISSUE THREAD

**Issue by MAXLZ1** [jaredwray/keyv#1227]
keyv.iterator is not a function when using KeyvEtcd.

```ts
const keyv = new Keyv(new KeyvEtcd('etcd://localhost:2379'));
  await keyv.set('key1', 'value1');
  await keyv.set('key2', 'value2');

  console.log(keyv.iterator); // TypeError: keyv.iterator(...) is not a function
  for await (const [key, value] of keyv.iterator()) {
    console.log(key, value);
  }
```

In fact, KeyvEtcd has an iterator.
https://github.com/jaredwray/keyv/blob/27c49a00c7c0b12875eec48b071cf297152644bf/packages/etcd/src/index.ts#L126-L136

**Comment by jaredwray** [comment]
Moving this to an enhancement as Keyv adapters do not need to provide iteration
