### ISSUE TITLE
`keyv` events does not respect `emitErrors` option

### ISSUE THREAD

**Issue by Sadzurami** [jaredwray/keyv#1248]
**Describe the bug**
In some cases `opts.emitErrors` does not handled or handled wrong.

Here, error will be thrown any way if store emits it and `opts.emitErrors` is false.

https://github.com/jaredwray/keyv/blob/68e37570a25ef94ea6f3cece066c8179c9aec7b5/packages/keyv/src/index.ts#L179-L181

https://github.com/jaredwray/keyv/blob/68e37570a25ef94ea6f3cece066c8179c9aec7b5/packages/keyv/src/index.ts#L223-L225

Here `emitErrors` is not mentioned.

https://github.com/jaredwray/keyv/blob/68e37570a25ef94ea6f3cece066c8179c9aec7b5/packages/keyv/src/index.ts#L540-L542

https://github.com/jaredwray/keyv/blob/68e37570a25ef94ea6f3cece066c8179c9aec7b5/packages/keyv/src/index.ts#L547-L554

**Comment by jaredwray** [comment]
@Sadzurami - thanks for the help on this! 🎉
