### ISSUE TITLE
KeyvRedis's namespace would be overrided by Keyv's namespace even not set

### ISSUE THREAD

**Issue by zhuxb711** [jaredwray/keyv#1254]
https://github.com/jaredwray/keyv/blob/676a7d250b29e6809d743399e1f6763887ec9b4d/packages/keyv/src/index.ts#L183

#### Keyv would override the KeyvRedis's namespace
```typescript
const test = new Keyv({
  store: new KeyvRedis(<cluster or url>, {
    namespace: 'my-namespace'
  })
})
```

**Comment by jaredwray** [comment]
Anytime Keyv is set it will override the store adapter namespace.
