### ISSUE TITLE
There is an option: 'useKeyPrefix' for Keyv but nowhere to set the keyPrefix

### ISSUE THREAD

**Issue by zhuxb711** [jaredwray/keyv#1255]
**Describe the bug**
Currently, it would use the namespace as the key prefix, which is weird. Should have an option: 'keyPrefix' instead of using namespace

If I create a Keyv like this
```typescript
const newKeyv = new Keyv({
  namespace: 'my-namespace',
  store: new KeyvRedis(<cluster or url>)
})
```
The actual key that store to redis would be: **my-namespace::my-namespace:my-key**

**Comment by zhuxb711** [comment]
I did some search on the source code, actual key should be:
`<KeyvRedis-Namespace><KeyvRedis-KeyPrefixSeparator><Keyv-Namespace>:<My-Key>`

Due to issue: #1254 , `KeyvRedis-Namespace` always equals to `Keyv-Namespace`

Therefore, it's impossible to make it store the key like this: `my-namespace:my-key` only on KeyRedis level
```typescript
const newRedis = new KeyvRedis(<cluster or url>, {
  keyPrefixSeparator: ':'
  namespace: 'my-namespace'
})
```

Workaround:
```typescript
const newKeyv = new Keyv({
  useKeyPrefix: false,
  namespace: 'my-namespace',
  store: new KeyvRedis(<cluster or url>, {
    keyPrefixSeparator: ''
  })
})
```

**Comment by jaredwray** [comment]
@zhuxb711 - I believe you should check out this in `@keyv/redis` which is an optimized version and sets the namespace correctly:

```js
import { createKeyv } from '@keyv/redis';

const keyv = createKeyv({ namespace: 'my-namespace' });
```

Here is the line of code that sets it correctly:
export function createKeyv(connect?: string | RedisClientOptions | RedisClientType, options?: KeyvRedisOptions): Keyv {

**Comment by zhuxb711** [comment]
> @zhuxb711 - I believe you should check out this in `@keyv/redis` which is an optimized version and sets the namespace correctly:
> 
> ```js
> import { createKeyv } from '@keyv/redis';
> 
> const keyv = createKeyv({ namespace: 'my-namespace' });
> ```
> 
> Here is the line of code that sets it correctly: export function createKeyv(connect?: string | RedisClientOptions | RedisClientType, options?: KeyvRedisOptions): Keyv {

createKeyv() do not support for cluster, it does not accept cluster as the connection

**Comment by zhuxb711** [comment]
> my-namespace:my-key

the createKeyv() will only create something like: `my-namespace::my-key` instead of `my-namespace:my-key`.
the only way to create `my-namespace:my-key` is code below:
```typescript
const newKeyv = new Keyv({
  useKeyPrefix: false,
  namespace: 'my-namespace',
  store: new KeyvRedis(<cluster or url>, {
    keyPrefixSeparator: ':'
  })
})
```

**Comment by jaredwray** [comment]
Gotcha. That is correct.
