### ISSUE TITLE
Why mongojs? -- Move to MongoDB Driver

### ISSUE THREAD

**Issue by dandv** [jaredwray/keyv#163]
Hi, any particular reasons why [mongojs](https://github.com/lukechilds/keyv-mongo/blob/852c74ed4c8dcafd6ff14d2ac364e795d295feee/package.json#L41) was [preferred to the official MongoDB driver](https://github.com/mafintosh/mongojs/issues/367) for Node? I'd like to take a stab at fixing the [failing tests](https://github.com/lukechilds/keyv-mongo/issues/22) and [the exit issue](https://github.com/lukechilds/keyv/issues/47). I've worked with the official driver package, but not with `mongojs`.

**Comment by jaredwray** [comment]
Moved to mono repo and working on moving to MongoDB driver 

https://github.com/jaredwray/keyv

**Comment by jaredwray** [comment]
@Jytesh and @Kikobeats - I looked at what you did on MongoDB Native driver and started a port back to this project. 

@Jytesh - is that what you were alluding too? :-) If so, it looks like it is failing on a single test which is this one. 

```
$ xo && nyc ava

  namespaced clear only clears current namespace

  Difference:

  - undefined
  + 'keyv2'

  › /Users/jaredwray/src/github.com/jaredwray/keyv/packages/test-suite/src/namespace.js:38:5
  › Generator.next (<anonymous>)
  › step (/Users/jaredwray/src/github.com/jaredwray/keyv/packages/test-suite/dist/namespace.js:7:191)
  › /Users/jaredwray/src/github.com/jaredwray/keyv/packages/test-suite/dist/namespace.js:7:361
  › runMicrotasks (<anonymous>)

  ─
  ```

Let me know your thoughts on if you want to fix it or I can.

**Comment by jaredwray** [comment]
Hello @dandv @chocolateboy @Jytesh this is now moved to the native driver and working. 🎉
