### ISSUE TITLE
Support mongodb gridfs

### ISSUE THREAD

**Issue by adityapatadia** [jaredwray/keyv#164]
When we use keyv-mongo for cache backend for [cacheable-request](https://github.com/lukechilds/cacheable-request), MongoDB does not allow files bigger than 16 MB. 

Can I implement mongodb gridfs to achieve the same? @lukechilds any thoughts about how should the API be?

**Comment by jaredwray** [comment]
@adityapatadia and @thgh - this is now part of the core MongoDB and will be fully live on NPM today. 

@adityapatadia - Would you like us to just list the idea as a contributor as we ended up not using any of your code but want to recognize your work on this. Just let us know!

**Comment by adityapatadia** [comment]
As you wish and whatever works best. :)

—
Regards,
Aditya Patadia

**Comment by jaredwray** [comment]
Will do. Working on adding in contributions as a listing :-)
