### ISSUE TITLE
Specify schema

### ISSUE THREAD

**Issue by s888** [jaredwray/keyv#165]
Can I connect Keyv to an existing table in db. How do I specify the schema?

I tried this
```
const keyv = new Keyv('postgresql://user:pass@localhost:5432/dbname', {schema: 'test', table: 'cache' });
```
But it is creating the table in pubic schema.

Thanks in advance

**Comment by jaredwray** [comment]
@alphmth - can we add this as an option for both `postgres` and `mysql`?

**Comment by alphmth** [comment]
@jaredwray yes working on it

**Comment by alphmth** [comment]
@jaredwray we can specify schema in postgres url like this `postgres://${dbUser}:${dbPass}@${dbHost}:${dbPort}/${dbName}?schema=${schema}`

Should I still add it as an option?

and I do not think we can not support for  mysql  as schema is a synonym for creating database

https://dev.mysql.com/doc/refman/8.0/en/create-database.html

**Comment by jaredwray** [comment]
Good to know on `postgres` will add this to documentation.

**Comment by jaredwray** [comment]
@s888 - looks like you would create the database with the schema and then mapping that user to the correct schema and keyv should work. Correct?
