### ISSUE TITLE
MySQL - Urgent security issues in `lodash` and `sql`

### ISSUE THREAD

**Issue by julian-weinert** [jaredwray/keyv#166]
I've just discovered (using `npm audit`) that there are some urgent and some minor issues.

• Package `sql` suffers from a not fixed SQL injection vulnerability (_not yet fixed_)
• Package `lodash` suffers from two urgent prototype pollution issues (_fixed in 4.17.11 and 4.11.17 respectively_)

Please consider updating `lodash` soon

**Comment by jaredwray** [comment]
@julian-weinert and @identithree this has been resolved and is now published. There are no reliance on SQL or other packages moving forward on mysql. 🎉
