### ISSUE TITLE
Error: Can't create more than max_prepared_stmt_count statements (current value: 16382)

### ISSUE THREAD

**Issue by Jeffthedevlol** [jaredwray/keyv#170]
Error: Can't create more than max_prepared_stmt_count statements (current value: 16382)
    at PromiseConnection.execute (/root/node_modules/mysql2/promise.js:102:20)
    at /root/node_modules/@keyv/mysql/src/index.js:19:30
    at /root/node_modules/@keyv/sql/src/index.js:35:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ER_MAX_PREPARED_STMT_COUNT_REACHED',
  errno: 1461,
  sqlState: '42000',
  sqlMessage: "Can't create more than max_prepared_stmt_count statements (current value: 16382)"
}

I'm using mysql, I've done some research although couldn't find a fix for this issue.

**Comment by jaredwray** [comment]
@Jeffthedevlol - is this during a large running process? Can you provide a code example that reproduces this?

**Comment by jaredwray** [comment]
@Jeffthedevlol - haven't heard back. Please let me know if you still are having issues with this and if you can provide a code example to produce the issue.

**Comment by banianxd** [comment]
I got this error too.
**Environment info:**
"keyv": "^4.0.3",
"@keyv/mysql": "^1.6.9",
db: amazon light sail mysql instance with version 8.0.34,
source project like 'https://github.com/AlmostEfficient/FaucetBot', which is a discord bot project. it leverages keyv features to save and retrieve data.

**Comment by banianxd** [comment]
> 

upgraded to the following version, but this issue did not disappear.
    "@keyv/mysql": "^1.6.10",
    "keyv": "^4.5.3"

**Comment by jaredwray** [comment]
is this only with Amazon? Also, do you have a usable test that we can validate this error?

**Comment by jaredwray** [comment]
@banianxd - I am trying to reproduce this and not able too so far. Is this only with Amazon? Also, do you have a usable test that we can validate this error?

**Comment by jaredwray** [comment]
going to close this until we can get some steps to reproduce.

**Comment by banianxd** [comment]
> > 
> 
> upgraded to the following version, but this issue did not disappear. "@keyv/mysql": "^1.6.10", "keyv": "^4.5.3"

with the upgraded  version, AND replace
 'const data = yield conn.execute(sql);' 
with
 'const data = yield conn.query(sql);' 
at line 63 of @keyv\mysql\dist\index.js,
it fixed the issue in my case and never happen again.

**Comment by jaredwray** [comment]
@banianxd - do you have a unit test that I can run that will show this error?

**Comment by jaredwray** [comment]
@Jeffthedevlol and @banianxd - this change has been made and will roll out with the next release in the next couple weeks.
