### ISSUE TITLE
@keyv/sqlite archived and has critical vulnerabilities

### ISSUE THREAD

**Issue by 174n** [jaredwray/keyv#171]
I just noticed @keyv/sqlite has critical vulnerabilities and the repo itself is archived. Is this project abandoned?

**Comment by paulmowat** [comment]
If you look at https://github.com/jaredwray/keyv/issues/147 you'll see they have moved to a mono-repo. So now all the projects are within this single repo. Just found same with redis repo as was looking at starting to use it.

**Comment by jaredwray** [comment]
@paulmowat and @174n - we are moving this to a mono repo and updating the packages this week. Sorry for the confusion and sqlite is now updated on NPM. 

We have updated redis already and should be pointing to the mono repo correctly.
