### ISSUE TITLE
Add repo migration notice to old repositories

### ISSUE THREAD

**Issue by wjhsf** [jaredwray/keyv#178]
After the migration to a mono repo (#147), the old repositories were archived, but there is no mention of why that was done. It would be helpful if there were a migration notice stating that the package is _not_ deprecated, it's just hosted in a different location now.

**Comment by jaredwray** [comment]
@wjhsf - Will thanks so much and we are working to update all NPM links now and should have that done in the next 10 days so it is not confusing. :-) 

Will keep this open until it is finished.

**Comment by jaredwray** [comment]
@wjhsf - this is all moved over and a notice has been placed on all archived repos. 

Thanks for finding this.
