### ISSUE TITLE
add .updater() / .wrap() method

### ISSUE THREAD

**Issue by mpodolsk** [jaredwray/keyv#205]
--UPDATED--

Could you add something like **.wrap()** in cacheman.

_Wraps a function in cache. The first time the function is run, its results are stored in cache so subsequent calls retrieve from cache instead of calling the function._

I think a lot of users are implementing something likes this by hand where it could be part of the interface.

example of this in similar lib https://github.com/cayasso/cacheman#cachewrapkey-work-ttl-fn

**Comment by jaredwray** [comment]
@mpodolsk - thanks for sending this in. We have looked at this in the past more around a middleware / handler functionality. Are you thinking something like this? 

‘’’
keyv.registerHandler(‘get’, someFunction);
‘’’

then when ‘get’ is called this function would always be called as a next step.

**Comment by mpodolsk** [comment]
Thinking about this more maybe this is actually not the best idea  😅  to make it a middleware.
I misrepresented what is done in cacheman. My bad 😭 

 ".get()"| is synchronous and adding middleware would change that / introduce non consistency in the .get() interface.
Better way would be to wrap the function in the cache. as the cacheman does, it just had foggy docs.

_Wraps a function in cache. The first time the function is run, its results are stored in cache so subsequent calls retrieve from cache instead of calling the function._

meaning

```js
const store = new Keyv({ttl: 3600});
const foo = async (x) => {
// does  something async
}
const wrappedFoo = store.wrap(foo)

module.exports = wrappedFoo

await wrappedFoo(x) // first time called, noting in cache, function runs output is cached in keyv
await wrappedFoo(x) // immediate response from cache
```

**Comment by jaredwray** [comment]
@mpodolsk not much traction around this request. Going to close it out and keep it back mind if other people ask for it or you are welcome to put together a pull request.
