### ISSUE TITLE
Clean Ghost Records (Sqlite)

### ISSUE THREAD

**Issue by TheCuteFoxxy** [jaredwray/keyv#214]
Is there a way to manually clean ghost records with the @keyv/sqlite package (either by running a script manually or something that is already implemented into keyv)?

**Comment by jaredwray** [comment]
Hi! There is currently no way to clean ghost records other than using the `.clear()` function which should clear out anything with the proper namespace. You can see the code we use here: https://github.com/jaredwray/keyv/blob/33e1a60d0411971efefc1718e64df55cab88c4cc/packages/sqlite/src/index.js#L67
