### ISSUE TITLE
Cannot store bigint and symbol values

### ISSUE THREAD

**Issue by dshepsis** [jaredwray/keyv#220]
### Problem
When using `Keyv#set`, an error is thrown if the `value` is a `symbol` or `bigint`, even though the documentation states that "Values can be of any type.". This also applies if the values are objects that contain one of those types.

For symbols, the error message is vague: 
```
SyntaxError: Unexpected token u in JSON at position 9
    at JSON.parse (<anonymous>)
    at Object.exports.parse [as deserialize] (C:\<project path>\node_modules\.pnpm\json-buffer@3.0.1\node_modules\json-buffer\index.js:49:15)
```

For bigints, the error message is more clear:
```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at stringify (C:\<project path>\node_modules\.pnpm\json-buffer@3.0.1\node_modules\json-buffer\index.js:45:17)
    at Object.stringify [as serialize] (C:\<project path>\node_modules\.pnpm\json-buffer@3.0.1\node_modules\json-buffer\index.js:32:37)
    at C:\<project path>\node_modules\.pnpm\keyv@4.0.5\node_modules\keyv\src\index.js:89:22
    at async C:\<project path>\test-keyv-symbol.js:10:4
```

### How to reproduce
Run this demonstration code in a directory with Keyv added as a dependency:
```js
const Keyv = require('keyv');

const testDB = new Keyv('sqlite://test.sqlite', { namespace: 'test' });
testDB.on('error', err => console.log('Connection Error', err));

(async () => {
	const values = ['Normal string value', 1, true, Symbol('Symbol value'), 1n, { foo: Symbol('Nested symbol value') }, { [Symbol('Symbol key')]: 'bar' }];
	for (const value of values) {
		try {
			await testDB.set('key', value);
			console.log('Success: ', await testDB.get('key'));
		}
		catch (error) {
			console.log('Failure: ', error);
		}
	}
})();
```
The output will show `Success:` lines for the first 3 values (string, number, and boolean), but show `Failure:` for the next 3 values (symbol, bigint, and an object containing a symbol). For the final value (an object with a symbol key), the output will show `Success:  {}`, which is effectively a silent failure.

### Expected behavior
My understanding is that it's impossible to serialize and de-serialize a `symbol`, because they are unique by definition. As such, the user should be clearly and eagerly warned when attempting to store them. Rather than the vague `undefined` JSON error or silent failure, an error message like `TypeError: Symbols cannot be serialized.` should be emitted whenever the value is a symbol or an object containing a symbol as a key or value.

For bigints, these should be serialized and de-serialized normally, like other primitives. 

### Version
4.0.5

**Comment by jaredwray** [comment]
@alphmth - it looks like you added in tests that make it so we cannot handle symbols. Is that correct?

**Comment by jaredwray** [comment]
@dshepsis - we have a fix coming in for bigint now but symbols might not be possible. We are looking into that.

**Comment by alphmth** [comment]
@jaredwray Symbol can not be serialized So I am just checking for symbol and returning error that `symbols cannot be serialized`

**Comment by jaredwray** [comment]
@alphmth - thanks for the information. 

@dshepsis - looks like we cannot to symbol.

**Comment by alphmth** [comment]
@dshepsis we can also use a custom serializer for BigInt as well perhaps using https://www.npmjs.com/package/json-bigint or something. 

Check [custom_serializers](https://github.com/jaredwray/keyv#custom-serializers)

**Comment by jaredwray** [comment]
> @dshepsis we can also use a custom serializer for BigInt as well perhaps using https://www.npmjs.com/package/json-bigint or something.
> 
> Check [custom_serializers](https://github.com/jaredwray/keyv#custom-serializers)

That would be great. Can we make sure to full test it?

**Comment by guotingchao** [comment]
This problem still exists at the moment。

```
 err: {
      "type": "TypeError",
      "message": "Do not know how to serialize a BigInt",
      "stack":
          TypeError: Do not know how to serialize a BigInt
              at JSON.stringify (<anonymous>)
              at defaultSerialize (/.../node_modules/.pnpm/@keyv+serialize@1.0.3/node_modules/@keyv/serialize/dist/index.cjs:64:15)

```

**Comment by jaredwray** [comment]
@guotingchao - you can fix this by using a custom serializer if you want. https://keyv.org/docs/keyv/#custom-serializers

**Comment by guotingchao** [comment]
> [@guotingchao](https://github.com/guotingchao) - you can fix this by using a custom serializer if you want. https://keyv.org/docs/keyv/#custom-serializers

Thank you. That's what I'm here for, to find a solution that will work.
