### ISSUE TITLE
More db methods

### ISSUE THREAD

**Issue by ririko5834** [jaredwray/keyv#226]
I would appreciate if you would add more methods, as quickmongo and quick.db has.

- push()
- pull()
- add()
- subtract()

```
 await db.push("userInfo.items", "Sword");
    // -> { difficulty: 'Easy', items: ['Sword'] }

    // Adding to a number (that doesn't exist yet) in an object:
    await db.add("userInfo.balance", 500);
    // -> { difficulty: 'Easy', items: ['Sword'], balance: 500 }

    // Repeating previous examples:
    await db.push("userInfo.items", "Watch");
    // -> { difficulty: 'Easy', items: ['Sword', 'Watch'], balance: 500 }
    await db.add("userInfo.balance", 500);
    // -> { difficulty: 'Easy', items: ['Sword', 'Watch'], balance: 1000 }

    // Fetching individual properties
    await db.get("userInfo.balance"); // -> 1000
    await db.get("userInfo.items"); // -> ['Sword', 'Watch']

    // remove item
    await db.pull("userInfo.items", "Sword");
    // -> { difficulty: 'Easy', items: ['Watch'], balance: 1000 }
```

**Comment by jaredwray** [comment]
@ririko5834 - thanks for asking this and we have looked at that in the past. For right now I am going to keep this here but as you can see there are other functionality just around `Map` that we want to focus on and extend onto. 

With this we would be extending what is standard across all the storage adapters. It might make more sense to build this as a super set on top.

**Comment by jaredwray** [comment]
@ririko5834 - after looking at this I think we are going to not do this as part of the core. If you would like to make an extension onto Keyv to support this we are happy to list it in the README. 

Thanks so much for posting on this.

**Comment by ririko5834** [comment]
I will wait until someone will make extension for it. I am not sure how to extend the core of keyv to implement those methods
