### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by dremekie** [jaredwray/keyv#252]
As mentioned in #64 , browser support would be useful . We're looking to run this in environments which are based on a web platform api (e.g. Cloudflare Workers).

Is there interest in addressing the two points of change mentioned in #64 ?
- Use https://www.npmjs.com/package/eventemitter3 instead of Node's built-in Event Emitter
- Use https://www.npmjs.com/package/buffer over using `json-buffer` which relies on Node's`Buffer`

**Comment by jaredwray** [comment]
@dremekie - thanks so much and I am adding this to a feature that we are going to look at in the next 90 days to implement. Do you have a use case that we can validate this against other than Cloudflare Workers? Would this help with other cloud providers serverless implementations?

**Comment by alfaproject** [comment]
I was just looking to see if there was a `localStorage` adapter and stumbled upon this ):

**Comment by jaredwray** [comment]
> I was just looking to see if there was a `localStorage` adapter and stumbled upon this ):

@alfaproject - make sure to upvote with a 👍 as we are evaluating if this makes senses.

**Comment by alfaproject** [comment]
I upvoted, thanks!

Client storage is getting increasingly more popular I think: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

We are trying to do more and more computation at the edge and preferably at the customers browser so we offset resources to the client or as close to the client as possible and I think that's getting more popular, especially with the whole serverless thing (;

**Comment by jaredwray** [comment]
> I upvoted, thanks!
> 
> Client storage is getting increasingly more popular I think: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
> 
> We are trying to do more and more computation at the edge and preferably at the customers browser so we offset resources to the client or as close to the client as possible and I think that's getting more popular, especially with the whole serverless thing (;

Interesting. Why would you want to use Keyv instead of just talking directly to these storage providers?

**Comment by alfaproject** [comment]
Because depending on the environment I might want to load a different provider. For example, in incognito I would use memory adapter because localStorage is not available. If I need to save more than 5mb of data, I would switch to IndexedDB without changing any of my cache code. Likewise, if I want to update our Cloudflare workers, I can either use their KV cache or their durable objects stuff, etc

Also, in the back-end we already use Keyv, so having a unified cache interface across the stack improves DX

**Comment by jaredwray** [comment]
@dremekie - we are looking at how hard this would be and what compatibility issues we would see by doing this. Should have an update in the next week or so.

**Comment by jaredwray** [comment]
@dremekie - we are now looking at an implementation for this.

**Comment by dremekie** [comment]
@jaredwray Thanks... that's great news

**Comment by jaredwray** [comment]
@dremekie @alfaproject - wanted to get an update to you. We found out that we need to do an architecture change on the caching layer before we make this work on the browser. Tracking it here: https://github.com/jaredwray/keyv/issues/407

**Comment by jimmywarting** [comment]
To better support browser then i would wish for 
- ESM
- use EventTarget instead of EventEmitter
- and use Uint8Array instead of Buffer

**Comment by radman-x** [comment]
Any updates on when browser support will be released?

**Comment by jaredwray** [comment]
@radman-x - this is still in planning for this year and we are first working on converting the project over to typescript. Once that is done then we will be building out the browser compatible version if possible. There is still some investigation on this. 

Also, we are looking at ESM but the focus is to make it as compatible as possible first.

**Comment by jaredwray** [comment]
Hi All. This is now in flight and I am going to close this and you can comment on this issue moving forward: https://github.com/jaredwray/keyv/issues/868
