### ISSUE TITLE
As a user I would like a package that handles keyv in offline mode

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/keyv#260]
This should be an alternative package that wraps Keyv and handles when the backend is not responding and then sync up when it is available.

**Comment by glensc** [comment]
I guess this is the "offline" adatpter? i read the name from adapters list, visited package readme:
- https://github.com/jaredwray/keyv/tree/26862ffb677013e88c82aec0de559a380d6e71e3/packages/offline

 and that made me scratch my head. wtf is it.

i read the source code, and it doesn't seem to do anything:
- https://github.com/jaredwray/keyv/blob/26862ffb677013e88c82aec0de559a380d6e71e3/packages/offline/src/index.ts

seems to proxy everything to keyv object. anyway this needs docs

**Comment by jaredwray** [comment]
@glensc - thanks for the note on this and with v5 coming out we will be deprecating this package.
