### ISSUE TITLE
TS2305: Module '"keyv"' has no exported member 'Store'.

### ISSUE THREAD

**Issue by adityap31** [jaredwray/keyv#269]
`tsc && vite build`

node_modules/@types/cacheable-request/index.d.ts(13,10): error TS2305: Module '"keyv"' has no exported member 'Store'.

**Comment by jaredwray** [comment]
@d-fischer, @Jmopel, @pavelkalin - moving this to an issue so we can track if the fix worked.

**Comment by jaredwray** [comment]
Verified that the system is building with changes.

**Comment by jaredwray** [comment]
@d-fischer - can you validate that the fix works when referencing current git? If so, I will version bump and publish to npm.

**Comment by d-fischer** [comment]
Builds fine for me.

**Comment by jaredwray** [comment]
With cacheable-request and got?

**Comment by d-fischer** [comment]
Yes, `@types/cacheable-request` is now compatible again.

**Comment by jaredwray** [comment]
@d-fischer - again thanks so much and I have now updated all NPM packages to latest with changes.

**Comment by adityap31** [comment]
Works! Thanks @jaredwray
