### ISSUE TITLE
Add an keyv.list() function

### ISSUE THREAD

**Issue by LACOSTAR91** [jaredwray/keyv#276]
## **Idea**

Add an `keyv.list()` function for get an list of all data in the database.

For example this function can return an Array of Object with an key and the value. Ex:
`[`
`{ key: "keyv", value: "https://npmjs.com/package/keyv" },`
`{ key: "discord.js", value: "https://npmjs.com/package/discord.js" },`
`{ key: "mysql", value: "https://npmjs.com/package/mysql" }`
`]`

**Comment by jaredwray** [comment]
@LACOSTAR91  - thanks and I believe you could use the iterators to get the data you are looking for. Have you tried that?

`keyv.iterator()`

We have not fully documented this feature yet but it should do the trick. You can look at this code example for it: 

https://github.com/jaredwray/keyv/blob/06102fc4a01115a42f0b6d2ced79ffdf7c47dcac/packages/test-suite/src/iterator.js#L4

**Comment by LACOSTAR91** [comment]
> @LACOSTAR91 - thanks and I believe you could use the iterators to get the data you are looking for. Have you tried that?
> 
> `keyv.iterator()`

I have already tried this but it doesn't work he return:

`Error: TypeError: this.keyv.iterator is not a function or its return value is not iterable`

But I don't know why I have this error. I have data in the database i'm sure.

**Comment by LACOSTAR91** [comment]
And here my code:

```js
for (const [key, value] of this.keyv.iterator()) {
      console.log(key, value);
      // channels.push(key);
};
```
