### ISSUE TITLE
Iterator function doesn't work

### ISSUE THREAD

**Issue by LACOSTAR91** [jaredwray/keyv#282]
I followed your instructions in the issue #276 (you have closed it)
But there is an error when using the iterator function.

Error: `TypeError: this.keyv.iterator is not a function or its return value is not iterable`

Code: 
```js
console.log(this.keyv.iterator()); // Return: Object [AsyncGenerator] {}
for (const [key, value] of this.keyv.iterator()) {
      console.log(key, value); 
};
```

_I have tried with no specified database to use in the Keyv class and with SQLite_

**Comment by jaredwray** [comment]
Ok. I will look into this and figure out why this is happening.

**Comment by LACOSTAR91** [comment]
@jaredwray Do you have an other version of keyv where the iterator function work ? Because I need this function for a code

**Comment by kennylbj** [comment]
Same issue when I tried to use iterator:
> iterator is not a function or its return value is not iterable

**Comment by kennylbj** [comment]
Both `keyv.iterator` and `keyv.iterator()` won't work.

Also, I found that the type definition of the "iterator" function is not exported, so I have to invoke it like this:

> (this.repo as any).iterator()

**Comment by lahed** [comment]
```
const iterator = keyv.iterator();
for await (const [key, raw] of iterator) {
    ...
}
```

**Comment by jaredwray** [comment]
Hello @LACOSTAR91 @kennylbj and @lahed - this feature set is in beta and it looks like it has not been plumped through the system. 

We are currently not able to focus on this feature set for a couple more weeks but then will get back to working on it.

**Comment by alphmth** [comment]
@LACOSTAR91 can you try what @lahed mentioned. It should work

**Comment by LACOSTAR91** [comment]
Yes I have tried it and it's work. It's juste the await he break all but without error

**Comment by jaredwray** [comment]
@LACOSTAR91 can you send us an example of this not working in code?

**Comment by LACOSTAR91** [comment]
This code doesn't work:
```js

console.log(this.keyv.iterator()); // Return: Object [AsyncGenerator] {}
for (const [key, value] of this.keyv.iterator()) {
      console.log(key, value); // Return nothing
};
```


This code work:
```js

console.log(this.keyv.iterator()); // Return: Object [AsyncGenerator] {}
for await (const [key, value] of this.keyv.iterator()) {
      console.log(key, value); // Return: key and value 
};
```

(Sorry for my bad English, I'm French)

**Comment by jaredwray** [comment]
Bo problem and thanks for the response

**Comment by kennylbj** [comment]
@jaredwray Thanks for the reminder, I have created a PR https://github.com/jaredwray/keyv/pull/295 to add documentation for this, please review.

**Comment by yaman3bd** [comment]
I am using keyv `5.0.1` and still the Iterator function does not work,
here is my setup:
```js
const Keyv = require("keyv").default;
const KeyvSqlite = require("@keyv/sqlite");
const CACHE_PATH = process.env.CACHE_SQLITE_URI || process.env.NEXT_PUBLIC_CACHE_SQLITE_URI;
const keyv = new Keyv({ store: new KeyvSqlite(CACHE_PATH) });

module.exports = keyv;
```
and here is how I am using it:
```js
require("dotenv").config();

const keyv = require("../lib/keyv");

async function logKeys() {
  const iterator = keyv.iterator(); //returns Object [AsyncGenerator] {}
  
  for await (const [key, raw] of iterator) {
    console.log(key, raw); // but nothing is logged
  }
}

logKeys();
```
I am sure that my sqlite file has values
my node version `v20.10.0`
npm version `8.19.1`
