### ISSUE TITLE
Please add sponsorship options

### ISSUE THREAD

**Issue by pgamerx** [jaredwray/keyv#294]
I don't know where I can donate to you, but your project has saved my life a lot of times and I would love to support you. I might only donate a small amount but you deserve it, man!

**Comment by jaredwray** [comment]
@pgamerx - thank you so much for the nice note and no need to support on this :-) so go ahead and give a small donation to a project that needs it. ❤️ 🙌

**Comment by pgamerx** [comment]
It's hard to find such humble and kind developers now-a-days, keep up the good work man!
