### ISSUE TITLE
Emit event when connection has been established

### ISSUE THREAD

**Issue by gnarea** [jaredwray/keyv#303]
Hi there,

First off, thank you so much for this library! I'm starting to play with it to integrate it in our code and it looks very much like what I've been looking for.

I think it'd be good if this lib emitted an event when the connection has been established, to complement the `error` event. I'd like to wrap my `Keyv` initialisation around something like this:

```typescript
async function initKeyv(url: string): Promise<Keyv> {
  const keyv = new Keyv(url);
  return new Promise((resolve, reject) => {
    keyv.once('connect', () => resolve(keyv));
    keyv.once('error', reject);
  });
}
```

... so that I have have local `try`/`catch` blocks to handle connection errors, which is impossible to do if the only event emitted is `error`.

As a partial workaround, I'm having to do something like this:

```typescript
import VError from 'verror';

function initKeyv(url: string): Keyv {
  const keyv = new Keyv(url);
  keyv.once('error', (err) => {throw new VError(err, `Keyv failed to connect to ${url}`)});
  return keyv;
}
```

... so that at least I have more context when the (unhandled) error is thrown. This is very important when troubleshooting, since some errors are very unhelpful and provide no context as to what exactly went wrong.

I know I could listen for the `connect` event in the underlying backend, but every backend is different and I'm planning to use Keyv precisely to write backend-agnostic code.

**Comment by gnarea** [comment]
Alternatively, this library could provide an `async` function that returned a `Keyv` object upon successful connection, so that I could use it as follows:

```typescript
let keyv : Keyv;
try {
  keyv = await Keyv.connect(url);
} catch (err) {
  throw new VError(err, `Keyv failed to connect to ${url}`)
}
```

**Comment by jaredwray** [comment]
@gnarea - thanks for sending this over. At this time we are not considering to do this as much of the current implementations would not be able to support this well unless we only did this at the main Keyv system as a single function that did the handling of the connection error. 

I am happy to keep this open to see if more people want this, but might not do this as there is currently a way of handling this.

**Comment by jaredwray** [comment]
@gnarea - going to close this out right now as there have not been asks for this.
