### ISSUE TITLE
Support ability to disconnect from backend manually

### ISSUE THREAD

**Issue by gnarea** [jaredwray/keyv#304]
Following up on the conversation on #131, I'm using keyv from a one-off script and the Node.js process hangs because there's an open socket.

I'm having to (partly) work around this by doing [the following](https://github.com/relaycorp/relaynet-pong/blob/7c524ceba71b6cc530506d929681a0b4bf080bf7/src/app/utilities/config/Config.ts#L29-L32):

```typescript
    const redis = (this.keyv.opts.store as KeyvRedis).redis;
    redis?.disconnect();
```

... which isn't ideal because my code is now Redis-aware and would still break when we support additional backends.

@jaredwray mentioned there's some interest in implementing `Keyv.disconnect()`, which would cause the underlying backend to disconnect from the server. That would solve this problem.

**Comment by jaredwray** [comment]
@gnarea - really love the idea of supporting this feature. The goal for this is to update all storage adapters to support this and make it easier to handle. 

Would it be ok if we did it as `async`?

**Comment by gnarea** [comment]
Excellent! Thanks @jaredwray! Yeah, async would be absolutely fine -- even ideal if the underlying adapter's disconnection method is async already.

**Comment by jaredwray** [comment]
@gnarea  - This is currently being tracked in a pull request by @alphmth here: https://github.com/jaredwray/keyv/pull/307

**Comment by jaredwray** [comment]
We have merged this pull request and will be handling a release this week. 🚀

**Comment by gnarea** [comment]
This is fantastic! Thank you so much!
