### ISSUE TITLE
pify dependency missing in @keyv/sqlite ?

### ISSUE THREAD

**Issue by ostling** [jaredwray/keyv#309]
After installing keyv + @keyv/sqlite and adding the basic example from readme i get this error:

Error: Cannot find module 'pify'
Require stack:
- mypath\node_modules\@keyv\sqlite\src\index.js
- mypath\node_modules\keyv\src\index.js
- mypath\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Object.<anonymous> (mypath\node_modules\@keyv\sqlite\src\index.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'mypath\\node_modules\\@keyv\\sqlite\\src\\index.js',
    'mypath\node_modules\\keyv\\src\\index.js',
    'mypath\\server.js'
  ]

Should probably have been added in commit 768014a72e722a0ea0ddae4a185fb16a022e6b08 unless I am missing something?

**Comment by baocancode** [comment]
I have just seen this issue as well, a walkaround is adding pify to my package.

**Comment by jaredwray** [comment]
@ostling and @baocancode do you have the steps to reproduce this? I did the following on a blank project and was able to have it work. 

`npm install keyv @keyv/sqlite`

Then I did the following code and it ran

```javascript
const Keyv = require('keyv');
const keyv = new Keyv('sqlite://database.sqlite');

await keyv.set('foo', 'never expires'); 
await keyv.get('foo');

```

**Comment by ostling** [comment]
Hi @jaredwray,
Thanks for checking this out!

I tested on basically the same code as you above and I get the error.
Node.js v18.1.0.
Created server.js with:
```
const Keyv = require('keyv');
const keyv = new Keyv('sqlite://sqlite.db');
keyv.set('foo', 'never expires');
keyv.get('foo');
```

package.json:
```
{
  "name": "keyvtest",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@keyv/sqlite": "^3.5.0",
    "keyv": "^4.2.2"
  }
}
```

Then run with "node server".

Are you running with some dev dependencies that maybe is using pify or how can it be in your node_modules?

**Comment by baocancode** [comment]
@jaredwray

- pify is a dev dependency of keyv https://github.com/jaredwray/keyv/blob/main/packages/keyv/package.json
- @keyv/sqlite does not declare pify as a dependency https://github.com/jaredwray/keyv/blob/main/packages/sqlite/package.json
- @keyv/sqlite does use pify https://github.com/jaredwray/keyv/blob/main/packages/sqlite/src/index.js

**Comment by baocancode** [comment]
Thanks, can you publish a new version for @keyv/sqlite which contains the fix?

**Comment by jaredwray** [comment]
version `3.5.1` is now live and published.
