### ISSUE TITLE
keyv/redis is not detecting external redis instance

### ISSUE THREAD

**Issue by sebaplaza** [jaredwray/keyv#310]
Hello,

I found a problem with [keyv/redis](https://github.com/jaredwray/keyv/tree/main/packages/redis).

When i try to use an existing redis instance as a parameter for `keyv/redis`, the library ignores it, and use the local default connection instead.

The origin is [this line](https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.js#L11) that uses `instanceof` to validate the redis instance, but validating against the local dependency of `ioredis`, not the external one.

I made a repo with the exemple: https://github.com/sebaplaza/keyv-redis-bug

Can we have a more flexible way to validate the redis client ?

Maybe declaring `ioredis` as a `peerDependency` ?

Thanks!

**Comment by jaredwray** [comment]
@sebaplaza thanks and we are looking into this more. We have been hesitate to declare ioredis as a dependency.

**Comment by sebaplaza** [comment]
@jaredwray it works !

```js
if (uri.options && uri.options.family) {
```

is a nice solution for this problem.

thanks !

**Comment by jaredwray** [comment]
@sebaplaza we just published `@keyv/redis` version `2.3.6` that has these changes in there.
