### ISSUE TITLE
Documentation: How to use the new built in compression on Keyv

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/keyv#322]
Keyv now has built in compression and it would be good to show the following:

- code examples of how to enable it
- overview of brotoli and the compression engine
- performance guidance (if possible)

This should be a stand alone markdown document using our standard practices

**Comment by kdybicz** [comment]
Hey @jaredwray ! I did debug the code step by step and this is what I got so far:

```
import Keyv from 'keyv';
import zlib from 'node:zlib';

const keyv = new Keyv(process.env.REDIS_HOST, {
  adapter: 'redis',
  compress: {
    opts: {
      // enable: false, // might be used to test purposes
      compressOptions: {
        [zlib.constants.BROTLI_PARAM_MODE]: zlib.constants.BROTLI_MODE_TEXT,
        [zlib.constants.BROTLI_PARAM_QUALITY]: zlib.constants.BROTLI_MAX_QUALITY, // zlib.constants.BROTLI_MIN_QUALITY,
      },
    },
  },
  maxRetriesPerRequest: 3,
  connectTimeout: 5000,
});
```
More info about this compression method you can find in: https://nodejs.org/api/zlib.html. As for performance, there is already a ton of materials about this topic in the Internet.

**Comment by jaredwray** [comment]
Hi @kdybicz - thanks for the info on this and it looks like you put together an issue on this. Will reply there as this is for somebody to create a readme markdown file for this project and less around troubleshooting.
