### ISSUE TITLE
Keyv v4.2.5 Error - Typescript Compiler Error

### ISSUE THREAD

**Issue by Nurutomo** [jaredwray/keyv#323]
Node: `v16.15.0`
Typescript: `4.6.4`
```
node_modules/keyv/src/index.d.ts:30:35 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

30  get<Raw extends boolean = false>(key: string | string[] = [], options?: {raw?: Raw}):
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/keyv/src/index.d.ts:45:9 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

45  delete(key: string | string[] = []): Promise<boolean>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/keyv/src/index.d.ts:30
```

**Comment by jaredwray** [comment]
@Nurutomo can you let is know what verson of Keyv you are using?

**Comment by misterjoshua** [comment]
I had this exact error in one of my auto-upgrade jobs. I'm running keyv@4.2.5. Here's an example of it failing:

Failing build: https://github.com/wheatstalk/cdk8s-node-script/runs/6361828485?check_suite_focus=true
Associated PR: https://github.com/wheatstalk/cdk8s-node-script/pull/93

**Comment by 2968yyc** [comment]
I have the same error.
nodejs 3.8.3; keyv: 4.2.5.
Then I change to keyv version 4.2.2 and don't have this issue.

**Comment by alexiwalker** [comment]
i am also getting this error, nodejs 16.13.1, typescript 4.5.2, keyv 4.2.5

**Comment by jaredwray** [comment]
We should have an update in tye next hour on this.

**Comment by jaredwray** [comment]
@theaussiepom - we are discussing the changes you are making here. https://github.com/jaredwray/keyv/pull/327

**Comment by jaredwray** [comment]
@theaussiepom, @2968yyc,  @misterjoshua, @Nurutomo - can you validate as we have published Keyv version `4.2.6`

**Comment by theaussiepom** [comment]
@jaredwray - this now builds correctly. Thank you for getting to this so quickly

**Comment by jaredwray** [comment]
> @jaredwray - this now builds correctly. Thank you for getting to this so quickly

Good to hear and thanks for the pull request 😄
