### ISSUE TITLE
Move keyv-memcache to @keyv/memcache

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/keyv#337]
Will NPM handle the redirect or do we need to do dual publishing? Need to validate this first

**Comment by alphmth** [comment]
@jaredwray we can [deprecate](https://docs.npmjs.com/cli/v8/commands/npm-deprecate) the current package and change package name in `package.json`. The warning will appear for current users like this `WARNING: This project has been renamed to {your-new-package-name}. Install using new-package-name instead.`

**Comment by jaredwray** [comment]
@alphmth - makes sense. Will get that scheduled for the next 30 days.
