### ISSUE TITLE
Iterator in TypeScript

### ISSUE THREAD

**Issue by DeveloperInProgress** [jaredwray/keyv#354]
I tried using the iterator in typescript this way:

```
for await (const [key,value] of this.keyv.iterator()) {
            
}
```

But I get this error:

```
Type 'AsyncIterator<[string, DeserializedData<string>], any, undefined>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator
```

How do I resolve this?

**Comment by jaredwray** [comment]
Hi @DeveloperInProgress I have not tested on Typescript but would assume this would work. 

```js
// please note that the "await" keyword should be used here
for await (const [key, value] of this.keyv.iterator()) {
  console.log(key, value);
};

Do you have a public code base example that I could pull down and test with?

**Comment by alphmth** [comment]
@DeveloperInProgress Can you check this https://stackoverflow.com/questions/47219503/how-do-async-iterators-work-error-ts2504-type-must-have-a-symbol-asynciterat

**Comment by DeveloperInProgress** [comment]
@jaredwray It doesn't seem to work for me. Here's the code: https://github.com/DeveloperInProgress/liquidation-bot/blob/bdb060161e5214b065bf84a0b5471ac380839f68/src/services/subscriptionService.ts#L87

**Comment by jaredwray** [comment]
@remon-nashid - That is a feature that we can enhance by defaulting to the namespace already provided.

**Comment by jaredwray** [comment]
Pull request coming in on namespace: https://github.com/jaredwray/keyv/pull/368

**Comment by jaredwray** [comment]
Release `4.3.1` should have a fix for this. Release notes https://github.com/jaredwray/keyv/releases/tag/2022-06-20

**Comment by DeveloperInProgress** [comment]
@jaredwray now I get a new error using iterator in TypeScript:
```
TypeError: this.keyv.iterator(...) is not a function or its return value is not async iterable
```

**Comment by jaredwray** [comment]
@DeveloperInProgress - thanks for the update and will check it out.

**Comment by DeveloperInProgress** [comment]
@jaredwray Thank you for reopening this issue, do we have any updates on this?

**Comment by alphmth** [comment]
@DeveloperInProgress @jaredwray 

I pushed a typescript example project [here](https://github.com/alphmth/keyv-iterator-ex). It works well in typescript

**Comment by jaredwray** [comment]
@DeveloperInProgress going to close this down as I validated this works also.

**Comment by phamleduy04** [comment]
Hi,

I tried @alphmth example project and it went well without a database driver. When I use etcd database, the error shows up again

Console without any database
```
npm run start

> cac-ex@1.0.0 start
> ts-node src/main.ts

foo:never expires
foo1:bar
foo2:bar2
finished
```

Console using etcd as database
```
npm run start

> cac-ex@1.0.0 start
> ts-node src/main.ts

/Users/dui/Desktop/test/keyv-iterator-ex/src/main.ts:14
  for await (const [key,value] of keyv.iterator()) {
                                       ^
TypeError: keyv.iterator(...) is not a function or its return value is not async iterable
    at testIterator (/Users/dui/Desktop/test/keyv-iterator-ex/src/main.ts:14:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jaredwray** [comment]
Etcd iteration has not been implemented at this time
