### ISSUE TITLE
level db storage adapter request 

### ISSUE THREAD

**Issue by gyn7561** [jaredwray/keyv#356]
https://github.com/Level/level

LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.

**Comment by jaredwray** [comment]
@gyn7561  - thanks for the request and we will keep this open for upvotes 👍 for people to add to for the next 60 days. Based on the interest we will consider it. 

Also, if you want to do a third party version we are happy to list that here: https://github.com/jaredwray/keyv#third-party-storage-adapters

**Comment by jaredwray** [comment]
@gyn7561 - there was not enough demand to do this at this time. Going to close this down.
