### ISSUE TITLE
lmdb db storage adapter request

### ISSUE THREAD

**Issue by gyn7561** [jaredwray/keyv#357]
https://github.com/LMDB/lmdb

https://github.com/kriszyp/lmdb-js

Symas LMDB is an extraordinarily fast, memory-efficient database we developed for the [OpenLDAP Project](http://www.openldap.org/)

**Comment by jaredwray** [comment]
@gyn7561  - thanks for the request and we will keep this open for upvotes 👍 for people to add to for the next 60 days. Based on the interest we will consider it. 

Also, if you want to do a third party version we are happy to list that here: https://github.com/jaredwray/keyv#third-party-storage-adapters

**Comment by jaredwray** [comment]
@gyn7561 - there was not enough demand to do this at this time. Going to close this down.

**Comment by sod** [comment]
https://www.npmjs.com/package/lmdb got quite popular. Would you be open if I contributed an adapter? The unified keyv interface is nice to chain caches. And lmdb file based cache is a good candidate to put in between a memory and a remote cache.

**Comment by jaredwray** [comment]
@sod - more than happy if you do a pull request to support it moving forward.
