### ISSUE TITLE
Redis.Cluster support is broken as of v2.3.6

### ISSUE THREAD

**Issue by jimmy-guzman** [jaredwray/keyv#385]
## Description

[This change](https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.js#L11) actually caused a breaking change for setups using `Redis.Cluster` since `uri.options.family` will not be defined when using `Redis.Cluster`

Doing `(uri.options && uri.options.family || uri.options && uri.isCluster)` will work but I haven't dug into ramifications of doing that.

## References
* [Default Cluster Options](https://github.com/luin/ioredis/blob/df04dd8d87a44d3b64b385c86581915248554508/lib/cluster/ClusterOptions.ts#L201-L217)
* [Default Redis Options](https://github.com/luin/ioredis/blob/df04dd8d87a44d3b64b385c86581915248554508/lib/redis/RedisOptions.ts#L188-L239)

**Comment by jimmy-guzman** [comment]
@jaredwray I'll create a reproduction repo shortly

**Comment by jaredwray** [comment]
@jimmy-guzman - any update on this? It would be good to show test code so we can validate against it.

**Comment by jimmy-guzman** [comment]
@jimmy-guzman here's a reproduction repo: https://github.com/jimmy-guzman/keyv-redis-bug-reproduction

I hope that helps.

**Comment by jaredwray** [comment]
@jimmy-guzman - thanks and we are working on this fix.
