### ISSUE TITLE
getMany returns empty array in case of all misses

### ISSUE THREAD

**Issue by AnotherGitProfile** [jaredwray/keyv#386]
## Description
The implementation of `get` method with array of keys returns empty array in case of missing values for all given keys https://github.com/jaredwray/keyv/blob/main/packages/keyv/src/index.js#L184. 

```javascript
const keyv = new Keyv();
await keyv.get(['foo', 'bar']) // returns []
await keyv.set('foo', 1);
await keyv.get(['foo', 'bar']) // returns [1, undefined]
```

Should it be designed to return array with the same size as keys array? Current behavior isn't clear and differs from popular storages like Redis MGET command.

**Comment by jaredwray** [comment]
@AnotherGitProfile - thanks for sending this in. I am interested in making this more standard and if you want to submit test examples around this we could look to validate it against other storage adapters to see if we can do this. 

Will be closing this but if you want to post more code on this we can re-open.
