### ISSUE TITLE
Expose Iterables

### ISSUE THREAD

**Issue by lukechilds** [jaredwray/keyv#40]
Add `.keys()`, `.values()` `.entries()` methods similar to the `Map` spec but instead they should return a Promise that resolves to an iterable.

Something like:

```js
const keyv = new Keyv();
await keyv.set('foo', 'bar');
await keyv.set('fizz', 'buzz');

const keys = await keyv.keys();
for (const key of keys) {
  console.log(key);
}
// 'foo'
// 'fizz'

const values = await keyv.values();
for (const value of values) {
  console.log(value);
}
// 'bar'
// 'buzz'

const entries = await keyv.entries();
for (const [key, value] of entries) {
  console.log(`${key} => ${value}`);
}
// 'foo => bar'
// 'fizz => buzz'
```

**Comment by chocolateboy** [comment]
> they should return a Promise that resolves to an iterable.

This requires *all* of the values to be slurped (or synchronously slurpable) before each method resolves, potentially incurring a huge cost in time and memory. What if there are a million records in a remote backend — taking, say, a minute to retrieve, and chewing through a gig of (mobile) RAM — but the caller only needs to check the first two?

```javascript
async function any (keyv, predicate) {
    const entries = await keyv.entries() // XXX uh-oh

    for (const [key, value] of entries) {
        if (predicate(key, value)) {
            return true
        }
    }
}
```

It would be more efficient to wait for a result, then process it, then wait for another result, then process that etc. The usual way to do this is not with a [recordset](https://en.wikipedia.org/wiki/Recordset) (e.g. a [promise which returns an array](https://github.com/lukechilds/keyv/pull/43)) but with a [cursor](https://en.wikipedia.org/wiki/Cursor_(databases)) (e.g. an [async iterator](http://2ality.com/2016/10/asynchronous-iteration.html)):

```javascript
async function any (keyv, predicate) {
    for await (const [key, value] of keyv.entries()) {
        if (predicate(key, value)) {
            return true
        }
    }
}
```

While *consuming* them in this way requires ES2018 (or Babel or [TypeScript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#async-iteration)), producing them does not (just as any library can spit out promises for consumption by async/await). And, of course, the desugared usage is always available as a fallback:

```javascript
async function any (keyv, predicate) {
    const it = keyv.entries()[Symbol.asyncIterator]()

    while (true) {
        const { done, value: pair } = await it.next()

        if (done) {
            return false
        }

        if (predicate(...pair)) {
            return true
        }
    }
}
```

**Comment by lukechilds** [comment]
@chocolateboy Thanks, great feedback.

We need to make sure the operation is atomic, this may be tricky iterating over entries in separate requests.

Or to be more specific, we need to make sure it is either guaranteed to be atomic on all storage adapters, or be clear there is no guarantee of atomicity on any storage adapter.

To be clear, the priority of Keyv is consistency over performance. If you need a highly performant key-value store you should probably pick an appropriate DB and use it directly. If you want reasonable perf for 90% of use cases and the added feature of consistent behaviour across a wide range of DBs, this is when you should pick Keyv.

That said, huge perf issues should still be avoided. You raise a good point re the potential issues with large datasets.

**Comment by chocolateboy** [comment]
Related: https://github.com/WICG/kv-storage/issues/6 ([via](https://developers.google.com/web/updates/2019/03/kv-storage))

**Comment by Chizz3x** [comment]
I just came here to check how to get all data from keyv db but all i see is just promises that it will be a thing. 'Cmon we need it!

**Comment by TehShrike** [comment]
"The ability to efficiently iterate over every record in a database" is such a potentially complex thing to implement – you don't want to force that on adaptor implementors.

If you want that behavior, use LevelUP – and then realize that the adaptor complexity is why so few LevelUP adaptors are actively maintained.

**Comment by vintprox** [comment]
@Chizz3x you can make a darn simple workaround: create key-key storage. This is object that will contain key, representing the name of "substorage", and each "substorage" will have array listing key names used in it.  Iterating through such array is easy-peasy.

**Comment by Chizz3x** [comment]
@vintprox Dang it, I couldn't think of that. Tysm
Btw sry if the previous comment looked rude.

**Comment by vintprox** [comment]
~~deleted previous comment~~

@Chizz3x 
You can utilize next walkaround: in each storage, add something like `_keys` entry, that should contain array listing all other keys used in respective storage.

**Comment by ApexCoder** [comment]
This worked for me:
`keyv.opts.store.query('SELECT * FROM keyv;');`

**Comment by kislball** [comment]
any updates?

**Comment by HiiZun** [comment]
`(bump)` i want to switch from quick.db to keyv to use a mysql/redis database this feature will help me a lot !

**Comment by HunteRoi** [comment]
> This worked for me:
> `keyv.opts.store.query('SELECT * FROM keyv;');`

It is a workaround. Also, querying every single record stored in keyv is firstly a huge perf shot and secondly might also be considered a security breach. Using this in production would open your program to bigger issues imo

**Comment by xcapt** [comment]
> > This worked for me:
> > `keyv.opts.store.query('SELECT * FROM keyv;');`
> 
> It is a workaround. Also, querying every single record stored in keyv is firstly a huge perf shot and secondly might also be considered a security breach. Using this in production would open your program to bigger issues imo

We used: 

`keyv.opts.store.query('SELECT **key** FROM keyv;');`

**Comment by vincilbishop** [comment]
One could subclass Keyv and override the set()/delete() methods to retain a list of keys that could be returned for later use.
