### ISSUE TITLE
Keyv.Options type incorrectly defines store option type

### ISSUE THREAD

**Issue by dylanseago** [jaredwray/keyv#404]
**Describe the bug**
The `Keyv.Options` type requires a type of `Store<Value>`, but all stores in this library appear to be implementing `Store<string | undefined>`. If the `Value` type is anything but `string` then using this option isn't possible, typescript will complain. This should be expecting a `Store<string | undefined>`, which also makes sense considering all values are, by default, serialized to string using JSONB before being passed down to the store.

**To Reproduce**
Via repo:
```
git clone git@github.com:dylanseago/keyv.git
git checkout repro-bad-store-types
yarn test:services:start
yarn test
```

Error:
```
  Uncaught exception in test/types.ts

  test/types.ts(13,15): error TS2769: No overload matches this call.
    Overload 1 of 2, '(options?: (Options<MyType> & Record<string, unknown>) | undefined): Keyv<MyType, Record<string, unknown>>', gave the following error.
      Type 'KeyvRedis' is not assignable to type 'Store<string | undefined>'.
        The types returned by 'getMany(...)' are incompatible between these types.
          Type 'Promise<string[] | undefined>' is not assignable to type 'StoredData<string | undefined>[] | Promise<StoredData<string | undefined>[]> | undefined'.
            Type 'Promise<string[] | undefined>' is not assignable to type 'Promise<StoredData<string | undefined>[]>'.
              Type 'string[] | undefined' is not assignable to type 'StoredData<string | undefined>[]'.
                Type 'undefined' is not assignable to type 'StoredData<string | undefined>[]'.
    Overload 2 of 2, '(uri?: string | undefined, options?: (Options<MyType> & Record<string, unknown>) | undefined): Keyv<MyType, Record<string, unknown>>', gave the following error.
      Argument of type '{ store: KeyvRedis; }' is not assignable to parameter of type 'string'.


  ✖ test/types.ts exited with a non-zero exit code: 1
  ─

  49 tests passed
  1 uncaught exception
```

**Expected behavior**
You should be able to instantiate a `Keyv` instance using `KeyvRedis` store in typescript.

**Tests (Bonus!!!)**
See https://github.com/dylanseago/keyv/blob/repro-bad-store-types/packages/redis/test/types.ts

**Additional context**
This bug likely impacts using more than just `KeyvRedis`, but that's what I'm trying to get working in typescript right now so it's what I added a test for.

**Comment by iamEAP** [comment]
Just chiming in to note that I get the same type error the new `@keyv/memcache` package too.

**Comment by jaredwray** [comment]
@dylanseago @t-botz and @iamEAP - we are looking at a fix for this and to make sure this gets resolved.

**Comment by alphmth** [comment]
@dylanseago @iamEAP Can you check this PR on your end? If its ok I will move forward with other packages. I have also added type tests that @dylanseago  wrote

**Comment by jaredwray** [comment]
@dylanseago  @t-botz and @iamEAP - we have merged this pull request (https://github.com/jaredwray/keyv/pull/405) and now validating it more under the `main` branch. 

@alphmth - it looks like you are working on the rest of the packages. Can you pull from main with the merged changes and continue wit your pull request?
