### ISSUE TITLE
Delete multiple keys in a single operation

### ISSUE THREAD

**Issue by lukechilds** [jaredwray/keyv#41]
Pass an array of keys to be deleted in a single operation.

```js
await keyv.delete(['key-1', 'key-2', 'key-3']);
```

Would be nice to have for performant deletion of multiple keys. However not sure this is gonna be feasible to implement without breaking `Map` compatibility.

**Comment by MySidesTheyAreGone** [comment]
You definitely can't have that if you want to keep the default store a simple Map(). However, you can create a wrapper around Map(), kinda like a keyv-map module but included in keyv instead of maintained separately.

**Comment by lukechilds** [comment]
I think you could just loop over the args if it's an Array and if `store` is an instance of `Map`.

Something like this:

```js
delete(key) {
	key = this._getKeyPrefix(key);
	const store = this.opts.store;
	return Promise.resolve()
		.then(() => {
			if (store instanceof Map && Array.isArray(key) {
				return Promise.all(key.map(key => store.delete(key)));
			}
			return store.delete(key)
		});
}
```

But that doesn't feel like a very neat solution.

**Comment by MySidesTheyAreGone** [comment]
Want me to toy with the idea and propose a couple of solutions? I'd rather do it once you're done with other core changes though

**Comment by yhjor** [comment]
https://github.com/MySidesTheyAreGone
yes please, a batch one would be nice
