### ISSUE TITLE
@keyv/redis printing "return"

### ISSUE THREAD

**Issue by shashankkr** [jaredwray/keyv#419]
**Describe the bug**
Hi, I am using the  "keyv": "^4.3.3", and  "@keyv/redis": "^2.3.8", and its printing "return" on the console. I can see the problem in the source: 
node_modules/@keyv/redis/src/index.js:57
<img width="395" alt="image" src="https://user-images.githubusercontent.com/244933/181653100-1e39bdf5-0f67-4b0b-8be9-85b97fe871a2.png">

**To Reproduce**
Please provide code that can be ran in a stand alone fashion that will reproduce the error. 

**Expected behavior**
No logs are written on the console

**Tests (Bonus!!!)**
If you want to provide unit test examples so that we can use this to validate the bug and then fix it will dramatically increase the possibility of this being resolved. 

**Additional context**

**Comment by jaredwray** [comment]
@shashankkr - hello. We just published `2.3.9` that has the fix in this.

**Comment by shashankkr** [comment]
thank you @jaredwray (been there done that :D)
