### ISSUE TITLE
Keyv.getMany - when all items are returned as `undefined` please return array of `undefined` instead of []

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/keyv#431]
**Is your feature request related to a problem? Please describe.**
Currently when getMany() returns all `undefined` it then gives just a blank array `[]`. Instead it should give an array of `undefined`. Example:

`['undefined', 'undefined', 'undefined']`

@trevor-scheer - would love any feedback on this as we are looking to make this change.

**Comment by trevor-scheer** [comment]
@jaredwray sounds good! The issue reads right to me. I'm not sure how each client behaves, I.e. null might be appropriate for some? I haven't looked, but just a consideration. Let me know when there's a PR I should look at! Thanks for handling this.

**Comment by jaredwray** [comment]
@trevor-scheer - agreed and will follow the thread and return what is native to the driver and system. We will begin work on this next week.

**Comment by jaredwray** [comment]
@trevor-scheer - changes have been made and if you want to verify it you can by pulling down the code. Our goal will be to release this in the upcoming 10 days.

**Comment by trevor-scheer** [comment]
Thanks! I'll keep my eyes peeled for the release. Quick glance at the changes lgtm.

**Comment by jaredwray** [comment]
Released 👉  https://github.com/jaredwray/keyv/releases/tag/2022-08-21
