### ISSUE TITLE
https://github.com/jaredwray/keyv/pull/433#issue-1343297829I think this should be `engines.node` if you want package managers to enforce this. This is also a breaking change for users running < v14. I would highly recommend a major version bump to accompany this change.

### ISSUE THREAD

**Issue by 1plansex1** [jaredwray/keyv#452]
I think this should be `engines.node` if you want package managers to enforce this. This is also a breaking change for users running < v14. I would highly recommend a major version bump to accompany this change.

_Originally posted by @trevor-scheer in https://github.com/jaredwray/keyv/issues/448#issuecomment-1221612007_

**Comment by jaredwray** [comment]
@1plansex1 - this was already take care of with the latest version
