### ISSUE TITLE
Documentation needs a clear link to the keyv module

### ISSUE THREAD

**Issue by chr15m** [jaredwray/keyv#476]
It is not clear to a new user coming to the Keyv repo from a search what the module actually does or how to use it. This information is now in the keyv module. There should probably be a prominent link to the keyv module where there is clear documentation explaining basic usage:

https://github.com/jaredwray/keyv/blob/main/packages/keyv/README.md

Thanks for maintaining this repo @jaredwray, much appreciated!

**Comment by jaredwray** [comment]
@chr15m - thanks for the info and we added an update [Getting Started](https://github.com/jaredwray/keyv#getting-started) to the mono repo to help with this and provide more clarity.
