### ISSUE TITLE
Provide esm version

### ISSUE THREAD

**Issue by tobiasdiez** [jaredwray/keyv#479]
**Is your feature request related to a problem? Please describe.**
With more and more build tools (vite, nuxt, etc) going towards an esm-first build, it would be nice if keyv could provide a proper [esm interface](https://nodejs.org/api/esm.html).

**Describe the solution you'd like**
Transpile and distribute esm version, including correct `export` declaration in `package.json` for all packages.

**Comment by jaredwray** [comment]
@tobiasdiez thanks so much for the feature request and we are looking at moving this to ESM over the next 6 months with some other major changes. Will keep this open for upvotes to prioritize.

**Comment by jaredwray** [comment]
@tobiasdiez - going to close this out as I have added this to the roadmap for 2023.
