### ISSUE TITLE
Allow passing SSL configuration into options for @key/postgres

### ISSUE THREAD

**Issue by wgwz** [jaredwray/keyv#527]
I recently found that I was unable to use the keyv postgres backend because the production database I was connecting to forces SSL connections. This is a request to add the ability to pass SSL configuration options into the Keyv object. Or more generally to allow passing external pool for Keyv to make use of.

These are a sample of the errors I was getting:

```
Error from keyv.Keyv: error: no pg_hba.conf entry for host "3.89.49.50", user "postgres", database "postgres", SSL off
```

And the more cryptic message (this occurs after the above error):

```
TypeError: query is not a function
  File "/app/node_modules/@keyv/postgres/src/index.js", line 29, col 19, in <anonymous>
    .then(query => query(sqlString, values));
  File "/app/node_modules/@keyv/postgres/src/index.js", in runMicrotasks
  File "node:internal/process/task_queues", line 96, col 5, in processTicksAndRejections
```

Here's a sample from my project of the SSL options:

```typescript
import * as fs from 'fs';
import { Pool, PoolConfig } from 'pg';

function setupPgPool(): Pool {
  const poolConfig: PoolConfig = {
    connectionString:
      process.env.DATABASE_URL ||
      'postgres://postgres:postgres@localhost:5432/regen_registry',
  };

  if (process.env.NODE_ENV === 'production') {
    poolConfig.ssl = {
      ca: fs.readFileSync(`${__dirname}/../config/rds-combined-ca-bundle.pem`),
    };
  }

  const pool = new Pool(poolConfig);
  return pool;
}

const pgPool = setupPgPool();

export { pgPool };
```

Here's an [upstream issue](https://github.com/regen-network/regen-registry/issues/1311) with some additional info in case it is helpful. I would be glad to work on this once an approach is decided.

**Comment by jaredwray** [comment]
@wgwz - Thanks for sending this over. It looks like we are not testing for SSL at this time and would be interested in adding it. Also, it looks like the link https://github.com/regen-network/regen-registry/issues/1311 is private or no longer working. 

Are you interested in doing a pull request?If not, more than happy to leave this for a vote to see if this will get any traction.

**Comment by wgwz** [comment]
hey @jaredwray thanks for the quick reply, and yes, i'm interested in working on a PR!

sorry about that link, i forgot it was private, but i did add most of the important info in the description. our tracker may end up public eventually, so we can just leave the link for now.

**Comment by jaredwray** [comment]
Great! Here is the guideline for doing a PR 👉 https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md

Let me know if you need any help as happy to jump in.

**Comment by jaredwray** [comment]
The first approach where we pass the config into @keyv/postgres storage adapter would be the preferred.
