### ISSUE TITLE
Add disconnect definition to the type declarations

### ISSUE THREAD

**Issue by ccortezaguilera** [jaredwray/keyv#558]
**Is your feature request related to a problem? Please describe.**
I wanted to expose the `disconnect` definition within the type declarations. The function exists [here](https://github.com/jaredwray/keyv/blob/fa388683edea4d29be523b8496f62c13e690299a/packages/redis/src/index.js#L104)
 but isn't declared in the type declarations. I wanted to extend the type and override some of the methods but the disconnect definition isn't defined in the type declarations.

**Describe the solution you'd like**
Defining the `disconnect` function within [this](https://github.com/jaredwray/keyv/blob/fa388683edea4d29be523b8496f62c13e690299a/packages/redis/src/index.d.ts#L6)
 file.

**Comment by jaredwray** [comment]
We will look to get this added for the next release.

**Comment by jaredwray** [comment]
This has been merged and will be out in the November release.
