### ISSUE TITLE
async deserialize call in iterator

### ISSUE THREAD

**Issue by sjourdois** [jaredwray/keyv#559]
Hi,

In packages/keyv/src/index.js, l. 69: `const data = this.opts.deserialize(raw);`
This should probably be: `const data = await this.opts.deserialize(raw);` : if using opts.compression, the deserialize function is async. Without this wait, the value is always null.

I don't know if that would break other usecases.

**Comment by jaredwray** [comment]
@sjourdois - thanks. We are looking into this.
