### ISSUE TITLE
AWS DocumentDB support

### ISSUE THREAD

**Issue by laurensV** [jaredwray/keyv#564]
Is there already a backend adapter for AWS DocumentDB (I see there is one for DynamoDB) or can the [@keyv/mongo](https://github.com/jaredwray/keyv/tree/master/packages/mongo) package be used for DocumentDB as well?

**Comment by jaredwray** [comment]
I have not tried the Mongo Storage adapter. Would be good to see if that is supported.

**Comment by jaredwray** [comment]
Looks like it should work. https://docs.aws.amazon.com/documentdb/latest/developerguide/connect_programmatically.html 

Do you want to verify?

**Comment by laurensV** [comment]
It works! just make sure you add `?tls=true` to your connection string and you have to add the path to the AWS SSL CA certificate file (https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem) in the options:
```
storage = new Keyv('your-document-db-connection-string?tls=true', {
        tlsCAFile: "rds-combined-ca-bundle.pem",
      });
```

**Comment by jaredwray** [comment]
That is great to hear. We will add some documentation for this also. Thanks for checking.
