### ISSUE TITLE
Question: keyv/redis - clear values from the set

### ISSUE THREAD

**Issue by PhantomRay** [jaredwray/keyv#565]
Hi there
Noticed that every time a cache entry gets added, it will also add the `key` under the set `namespace:keyv`. https://github.com/jaredwray/keyv/blob/fcc8f3a7871a7ff9e640bf677c0f0aa3f689807b/packages/redis/src/index.js#L55

Even though there is `redis.srem` under the implementation of `delete()` and `clear()`, but I don't think it's ever called.

Any suggestions on how to clear the set?

**Comment by jaredwray** [comment]
Hello - we are looking to not use the namespace moving forward and are planning a rebuild of Redis in Q1 2023. FYI on this here: https://github.com/jaredwray/keyv/issues/455

**Comment by jaredwray** [comment]
We are working on it and it might take until January to get it live.
________________________________
