### ISSUE TITLE
Documentation and example to setup

### ISSUE THREAD

**Issue by lalit774** [jaredwray/keyv#614]
I want to explore this project. But it has limited documentation. How can i configure with backstage?

**Describe the solution you'd like**

**Comment by jaredwray** [comment]
Hi @lalit774 - thanks for the ask and here is our initial getting started guide that we have been working on. https://github.com/jaredwray/keyv/blob/main/docs/getting-started/index.md

Feel free to use that. 

On backstage I see that you posted this: https://github.com/backstage/backstage/issues/15116

One note is that if you have a large amount of caching I would recommend to use memcache as Redis sometimes does not clear the memory (we are working on a fix)

You can see the usage here but I wasn't able to find how to set it up: https://backstage.io/docs/reference/backend-common.cacheclient and the options are here: https://github.com/backstage/backstage/blob/38c3c4931aec757e3d739591b194b7ca5f56267f/packages/backend-common/src/cache/CacheManager.test.ts#L57
