### ISSUE TITLE
[Question/Unwanted Documentation?] Tiered storage adapter stores values inside values

### ISSUE THREAD

**Issue by IceToast** [jaredwray/keyv#635]
Hey, first of all thanks for all your work. Keyv and the storage adapters are working very well!

I noticed that the documentation for the tiered storage adapter want you to put the tiered store inside another keyv store
```
const store = new KeyvTiered({remote, local});
const keyv = new Keyv({store});
keyv.on('error', handleConnectionError)
```
Basically it works as intended except that the db entry for the remote store (mysql for example) now has two namespaces (from the remote store and the normal store where the tiered is saved) and also stores the value as a nested value, which seems a bit odd.

From my remote store
```
key: system.test
value: {"value":"{\"value\":\"test\",\"expires\":null}","expires":null}
```

Is that the intended behavior when using the tiered storage adapter?

Note: Just using the tiered store does not have this behavior.

**Comment by jaredwray** [comment]
@IceToast - thanks for the information and yes the nested is included with the current architecture as it is adding multiple layers to the Keyv engine. Basically, we are using 2 different layers.

You are correct that you could just use KeyvTiered and not Keyv to remove this layering behavior. 

If you want to do a pull request and update the documentation that would be amazing.
