### ISSUE TITLE
Express Session Store Wrapper

### ISSUE THREAD

**Issue by lukechilds** [jaredwray/keyv#637]
[`express-session`](https://github.com/expressjs/session) stores sessions in memory by default for dev and supports a `store` option for persisting sessions in production. They list some popular stores [here](https://github.com/expressjs/session#compatible-session-stores) however many of these are poor quality or unmaintained.

The API for implementing an `express-session` store is very similar to Keyv's API. Docs are here: https://github.com/expressjs/session#session-store-implementation

It should be pretty straight forward to implement a `keyv-express-session-store` wrapper that allows any Keyv storage adapter to be used to back an Express apps session store.

The API could be something like:

```js
import express from 'express'
import session from 'express-session'
import Keyv from 'keyv'
import KeyvExpressSessionStore from '@keyv/express-session-store'

// One of the following
const keyv = new Keyv();
const keyv = new Keyv('redis://user:pass@localhost:6379');
const keyv = new Keyv('mongodb://user:pass@localhost:27017/dbname');
const keyv = new Keyv('sqlite://path/to/database.sqlite');
const keyv = new Keyv('postgresql://user:pass@localhost:5432/dbname');
const keyv = new Keyv('mysql://user:pass@localhost:3306/dbname');
const keyv = new Keyv('etcd://localhost:2379');

const app = express()
app.use(session({
  secret: 'correct horse battery staple',
  store: new KeyvExpressSessionStore(keyv),
}))
```

This would be really neat because then Express users can benefit from all the high quality well maintained Keyv storage adapters for free.

I'm not able to dedicate time towards working on this right now but the idea just popped into my head so I wanted to throw it out there incase anyone thinks it's worth working on.

**Comment by jaredwray** [comment]
@lukechilds - thanks for adding this in and will get some voting going.

**Comment by stanislavnastasiu-dev** [comment]
that would be great!

**Comment by jaredwray** [comment]
@lukechilds and @stanislavnastasiu-dev - I will be adding you to a new project that will handle this problem specifically in the next 60 days. Closing this as it wouldnt be with Keyv but more of a module above this.

**Comment by tsibley** [comment]
Came here to see if someone else had asked the same question / found an answer… doesn't look like it exists though? I'd prefer to not write this myself! :upside_down_face:

**Comment by jaredwray** [comment]
@tsibley - we will be working on this in the new year under `cacheable` project.

**Comment by tsibley** [comment]
Ah, ok, thanks for the update!
