### ISSUE TITLE
Code highlighting, improvements, etc

### ISSUE THREAD

**Issue by Viiprogrammer** [jaredwray/keyv#677]
**Missing code highlighting:** https://github.com/jaredwray/keyv/tree/main/packages/mysql#ssl

Maybe add [memcache example with URI](https://github.com/jaredwray/keyv/tree/main/packages/memcache#usage), [here](https://github.com/jaredwray/keyv/tree/main/packages/keyv#usage) ?

Variable with `server` not used (+ replace `let` to `const` ?) - https://github.com/jaredwray/keyv/tree/main/packages/memcache#using-memcached

Replace `let` to `const` ?
1. https://github.com/jaredwray/keyv/tree/main/packages/memcache#usage
2. https://github.com/jaredwray/keyv/tree/main/packages/memcache#usage-with-namespaces
3. https://github.com/jaredwray/keyv/tree/main/packages/memcache#using-memcachier
4. https://github.com/jaredwray/keyv/tree/main/packages/memcache#using-redislabs-memcache-protocol

Make description [starts with upper letter](https://github.com/jaredwray/keyv/tree/main/packages/offline)? `offline storage adapter for Keyv` → `Offline storage adapter for Keyv`

**Comment by jaredwray** [comment]
@Viiprogrammer - thanks so much and we are working on making this better. If you would like to do a couple of pull requests that would be great. Otherwise we will get to this over the next 30 days.
