### ISSUE TITLE
Cassandra Db support 

### ISSUE THREAD

**Issue by MEZBATHEKING** [jaredwray/keyv#696]
Datastax.com Cassandra Database Support for keyv pls

**Comment by jaredwray** [comment]
@MEZBATHEKING - thanks for the suggestion and if you are interested it would be great if you want to build a third party driver like the following:

https://github.com/jaredwray/keyv#third-party-storage-adapters

We will add this as something to vote on to see if it gets traction.

**Comment by prohooks-y** [comment]
This would be cool 👍

**Comment by jaredwray** [comment]
Looks like there are a couple votes here so far. I am not planning to work on this at this time but if you want to build this adapter and make it into a pull request we are happy to help on it. 

@prohooks-y, @MEZBATHEKING?
