### ISSUE TITLE
bug: KeyvRedis key prefix namespace behavior is not consistent with Keyv

### ISSUE THREAD

**Issue by titanism** [jaredwray/keyv#700]
As seen here <https://github.com/jaredwray/keyv/blob/823fffe4bf096a341ec82b7f3e38f7cc1897ee42/packages/keyv/src/index.js#L188>, `Keyv` utilizes the `namespace` option for `get` and `set`.  However `KeyvRedis` does not at <https://github.com/jaredwray/keyv/blob/823fffe4bf096a341ec82b7f3e38f7cc1897ee42/packages/redis/src/index.js#L41>.

**Comment by jaredwray** [comment]
@titanism Let me know if you plan to use this project or the other one. If the other one we should close this.
