### ISSUE TITLE
 in nestjs throw a exception of default is not a constructor

### ISSUE THREAD

**Issue by halower** [jaredwray/keyv#701]
**Describe the bug**
[Nest] 8296  - 2023/03/04 10:11:56   ERROR [ExceptionHandler] redis_1.default is not a constructor
TypeError: redis_1.default is not a constructor

**How To Reproduce (best to provide workable code or tests!)**
```
    import KeyvRedis from '@keyv/redis'
    import Keyv from 'keyv'
   ... 
   const redisUrl = process.env.REDIS_URL || 'redis://localhost:6379'
    const store = new KeyvRedis(redisUrl) 
    this.messageStore = new Keyv({ store, namespace: 'demo' })

   ------------------
      "@keyv/redis": "^2.5.5",
    "keyv": "^4.5.2",
```

**Comment by jaredwray** [comment]
hi @halower - can you provide more of the code from nestjs or a sample set to reproduce?

**Comment by halower** [comment]
我使用以下方式解决了

```javascript
import * as KeyvRedis from '@keyv/redis'
 import * as Keyv from 'keyv'
```
i need to test it, thanks

**Comment by jaredwray** [comment]
going to close the issue.
