### ISSUE TITLE
Ability to not use a namespace

### ISSUE THREAD

**Issue by dandv** [jaredwray/keyv#72]
I would also (#48) like the ability to not use a namespace. The use case is easier debugging without having to mentally parse out the `keyv:` prefix from every value. Plus, with MongoDB, collections are a cleaner and simpler way to achieve namespacing.

**Comment by lukechilds** [comment]
I can definitely see the benefits of not requiring a namespace.

>with MongoDB, collections are a cleaner and simpler way to achieve namespacing

Seems like this should be handled by the MongoDB storage adapter, not Keyv itself.

**Comment by jaredwray** [comment]
@dandv - going to close this down as there has been little traction on this.
