### ISSUE TITLE
When call keyV.set with constant as 3rd param, ttl is not set

### ISSUE THREAD

**Issue by pkellner** [jaredwray/keyv#721]
When calling like this:  

`keyV.set(cacheKey,  returnImageString, 10000);`

the ttl is not set

when calling like this, the ttl is set.
const cacheSeconds = 10;
`keyV.set(cacheKey, returnImageString, cacheSeconds * 1000);`

```
  "keyv": "^4.5.2",
  "@keyv/redis": "^2.5.5",
```

**Comment by jaredwray** [comment]
Hi @pkellner - I was not able to duplicate this and also created a unit test with the current code base. Going to close this down unless you can let me know how to reproduce: https://github.com/jaredwray/keyv/blob/4591836f9c7a5828662f56e585e7e1af4ae115f0/packages/redis/test/test.js#L113

**Comment by pkellner** [comment]
Probably a Webpack issue.  I’ve seen similar around typing Cause of code rewrites.  
thanks for checking.
