### ISSUE TITLE
Allow client to opt out of using namespace

### ISSUE THREAD

**Issue by klippx** [jaredwray/keyv#729]
**Is your feature request related to a problem? Please describe.**
We have a legacy system that has keys on the form `cce-integration-layer-compressed:StateShortner-${randomId}` that we need to be compatible with (we read/write to a shared redis instance with that legacy system) so there is no room for a namespace colon... 

However, not only is namespace defaulting to `keyv`, even if you give it empty string you still get ':' which messes up our ability to use keys on the expected form!

We really want/need to migrate to keyv, we are blocked due to namespace. The reason we want to use this project is because it is the recommended cache backend for [Apollo Server 4](https://www.apollographql.com/docs/apollo-server/performance/cache-backends#configuring-redis)

For all our other use cases of keyv the namespace is great, but in this case it is really causing problem that cannot be worked around...

**Describe the solution you'd like**
 I wish I could pass in e.g. `const keyv = new Keyv({ store: keyvRedis, namespace: false })` and get rid of the whole `<namespace>:` part.

PS: Related to #120 but this is 3 years old so I reckoned it was better to open a new issue.

**Comment by jaredwray** [comment]
Adding vote option

**Comment by jaredwray** [comment]
This was turned down due to some of the complexities of the system. We are looking at this feature for a new Redis driver specifically. Are you using Redis as your primary?

**Comment by jaredwray** [comment]
@klippx - going to look at adding this feature to Redis storage adapter in another issue: https://github.com/jaredwray/keyv/issues/455

**Comment by klippx** [comment]
We are using Redis as our primary, yes. Basically, it is a "keyv+redis" combo, that comes as a package deal with Apollo Server 4.

**Comment by jaredwray** [comment]
Great. we are working on an updating version on the branch `redis-next` and will look to make the namespace for redis an option with a couple other features.
