### ISSUE TITLE
Feedback on `TTL` behavior

### ISSUE THREAD

**Issue by klippx** [jaredwray/keyv#733]
**Is your feature request related to a problem? Please describe.**

Thanks for the library, I find the design pattern sound. But as a new user to this library I wanted to share some feedback. 

First, let me share our example usage so you can gauge the API look and feel:

```ts
import KeyvRedis from '@keyv/redis';
import { KeyvAdapter } from '@apollo/utils.keyvadapter';
import { BaseRedisCache } from 'apollo-server-cache-redis';
import Redis from 'ioredis';
import Keyv, { DeserializedData } from 'keyv';

const redis = new Redis({ ... })

const keyvRedis = new KeyvRedis(redis);

const keyv = new Keyv({
  store: keyvRedis,
  namespace: dgsName,
  // Sidestep `keyv` behavior and WRITE values as `T` (instead of DeserializedData<T> which is basically `{value:T,expires:U}`)
  serialize: ({ value }) => value,
  // Sidestep `keyv` default behavior to not parse data automatically; but still return it "as if" it was stored like DeserializedData
  deserialize: (data: string) => {
    return { value: data, expires: undefined };
  },
});
const adapter = new KeyvAdapter(keyv);
```

#### Manual TTL handling

The first thing that caught be off guard was that `keyv` saves data not as `T` but as `{"value":T,expires:<number>}`. And then it does "manual" ttl by removing stuff from cache _on read_. 

I think this would be best described as a "a poor man's TTL" which is on by default for all adapters (redis is one where it makes no sense at all).

Now, using Redis which has built in TTL, you really have to go out of your way to opt out of the poor mans version as you can see above. My gripe is that I need to specify 2 options, where I need to be aware of the poor man implementation and sidestep it.

The only reason why you save values of `T` as `DeserializedData<T>` instead is to do this poor man's TTL. which from a software architecture point of view it is also a very naive implementation. 

**Describe the solution you'd like**
Get rid of the manual TTL as a core `keyv` feature! TTL is a thing that should be a separate, optional, and off by default package, something that you opt in to explicitly using an adapter. Don't let it be a core feature, core features be normal and sound, not littered with questionable features that makes no sense for all adapters.

Also, the type signatures should change accordingly:
```
		/** A custom serialization function. */
		serialize?: ((data: Value) => string) | undefined;
		/** A custom deserialization function. */
		deserialize?: ((data: string) => Value | undefined);
```

I realize this is a breaking change, which is painful, but it evolves the library in the correct direction. It is backwards compatible if users opt in to this hypothetical adapter anyway (which can possibly fix `deserialize` and `serialize` under the hood).

This will lead to simpler API with Least Element of Surprise, easier to document and cover the base use cases better across all adapters.

**Comment by jaredwray** [comment]
@klippx - thanks for your feedback and while I understand your opinion on the `raw` option this was built in the past for internal usage on other storage adapters. There is a re-write going on for redis which will make this a bit better and we hope to have out soon.

**Comment by klippx** [comment]
Hi, I think you left the same answer here as in #734 but in this issue I didn't talk about `raw` option. What is your take on my hot take regarding getting rid of manual `TTL` (and deleting as a side effect) as a core feature?
