### ISSUE TITLE
Feedback on `get` API

### ISSUE THREAD

**Issue by klippx** [jaredwray/keyv#734]
**Is your feature request related to a problem? Please describe.**

Related to #733, I wanted to share some more feedback. 

Again, our example usage so you can gauge the API look and feel:

```ts
import KeyvRedis from '@keyv/redis';
import { KeyvAdapter } from '@apollo/utils.keyvadapter';
import { BaseRedisCache } from 'apollo-server-cache-redis';
import Redis from 'ioredis';
import Keyv, { DeserializedData } from 'keyv';

const redis = new Redis({ ... })

const keyvRedis = new KeyvRedis(redis);

const keyv = new Keyv({
  store: keyvRedis,
  namespace: dgsName,
  // Sidestep `keyv` behavior and WRITE values as `T` (instead of DeserializedData<T> which is basically `{value:T,expires:U}`)
  serialize: ({ value }) => value,
  // Sidestep `keyv` default behavior to not parse data automatically; but still return it "as if" it was stored like DeserializedData
  deserialize: (data: string) => {
    return { value: data, expires: undefined };
  },
});
const adapter = new KeyvAdapter(keyv);
```

#### `raw` option in `get(key, options)`

This option is undocumented, and it is bad. It seems to me that this is a cheap shot at reading values without applying `.value` on the deserialized data, which means you can solve all use cases it provides using `deserialize` instead. It is redundant, undocumented, and clunky. 

Like in my case, I can't affect how `BaseRedisCache` uses `keyv`, and in fact they do `get(key)` without options, but I could solve my problem using `deserialize` instead which lives on `Keyv` over which I have full control. 

**Describe the solution you'd like**
`raw` is not useful, it only works for `get`, and doesn't exist for `set`, and in the case where there are third party libraries most likely 99.9999% they are not going to expose this option and just use plain `get` anyway giving NO control to the end user.

It is totally redundant anyway! Please get rid of it in the next breaking, nobody needs this.

EDIT: If your test coverage is good enough you can try and see if you can solve it using `deserialize` instead.

**Comment by jaredwray** [comment]
@klippx - thanks for your feedback and while I understand your opinion on the `raw` option this was built in the past for internal usage on other storage adapters. There is a re-write going on for redis which will make this a bit better and we hope to have out soon.
