### ISSUE TITLE
[@keyv/redis] add option to use RedisJSON instead of default api

### ISSUE THREAD

**Issue by sebaplaza** [jaredwray/keyv#769]
**Is your feature request related to a problem? Please describe.**

Hello, 

Redis has a new way to store json documents, this can avoid the stringify/parse operation when saving a json object.

This is a high cpu consuming operation.

**Describe the solution you'd like**

Would be great to have an option to use the [RedisJSON api](https://redis.io/docs/stack/json/) when we have a recent redis server (like redis-stack) with RedisJSON support 

Here is a simple guide to use this api

https://developer.redis.com/howtos/redisjson/using-nodejs

**Edit** : After a research, i see that there is no magic here... the redis client is only wrapping the stringify/parse part. So, i don't know if this issue is interesting to develop in a cache library.

https://github.com/redis/node-redis/blob/master/packages/json/lib/commands/index.ts#L74

**Comment by jaredwray** [comment]
Agree that this most likely would not make sense at this time to add.
