### ISSUE TITLE
keyv-arango is not usable

### ISSUE THREAD

**Issue by robross0606** [jaredwray/keyv#785]
I know it is listed as a third-party module, but you may want to reconsider including it as a compatible storage adapter until it is functional.  The package is not installable via `npm` because it is packaged incorrectly.  Refer to https://github.com/TimMikeladze/keyv-arango/issues/3

**Comment by TimMikeladze** [comment]
Author of the keyv-arango package here. I believe the packaging issue has been resolved, I have published a new version to `npm` and made sure it's installable via `npm` in a new project.

**Comment by robross0606** [comment]
Confirmed this has been resolved.
