### ISSUE TITLE
Get all entries

### ISSUE THREAD

**Issue by MEZBATHEKING** [jaredwray/keyv#786]
Hello there . I would like to request a feature called "Get All Entries".
It will be like you can get all Keyvalue entries in Array of the database. It should be like
[
{ "Key": "value" },
{ "Key2": "val2"},
]

**Comment by jaredwray** [comment]
Hi @MEZBATHEKING - Thanks for the question and the only way to do this is to use the iterator method. Here 

https://github.com/jaredwray/keyv/tree/main/packages/keyv#iterator
