### ISSUE TITLE
Filter out more options for a valid mysql2 connection configuration object

### ISSUE THREAD

**Issue by kossidts** [jaredwray/keyv#788]
**Mysql2 warnings on invalid options**
I am currently seeing this warnings which might lead to breaking changes in future:
```
Ignoring invalid configuration option passed to Connection: adapter. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: table. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: keySize. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
```

**How To Reproduce (best to provide workable code or tests!)**
After having installed `keyv` v4.5.2, `@keyv/mysql` v1.6.3 as well as `mysql2` v3.2.3, run the following code:
```js
const myCache = new Keyv({
    uri: '<connection-string>',
    adapter: "mysql",
    table: "memory_cache",
    keySize: 255,
    namespace: 'global'
});
```

**Comment by kossidts** [comment]
I would gladly provide a fix, but I can't get this package (I forked the repo) up and running. I am currently running node v16.13.1 on MacOs 12.6.3 / M1 Pro with docker installed. I do have installed yarn for the first time.

`yarn test:services:start` seems to work find but `yarn test` fails with: 

```sh
src/index.ts:1:45 - error TS2307: Cannot find module 'node:zlib' or its corresponding type declarations.
src/index.ts:2:28 - error TS2307: Cannot find module 'compress-brotli' or its corresponding type declarations.
src/index.ts:21:3 - error TS2578: Unused '@ts-expect-error' directive.
src/types.ts:1:63 - error TS2307: Cannot find module 'node:zlib' or its corresponding type declarations.
src/types.ts:2:69 - error TS2307: Cannot find module 'json-buffer' or its corresponding type declarations.
[...]
error Command failed with exit code 2.
```

**Comment by jaredwray** [comment]
Hi! You will want to run the commands in order from the root of the mono project:
- yarn
- yarn test:services:start
- yarn test

**Comment by kossidts** [comment]
Great thanks. It works ;)

**Comment by jaredwray** [comment]
Awesome. Let me know if you have any questions and thanks for offering to do a pull request.

**Comment by maxijonson** [comment]
Hey! I see this issue was closed with no PR. Is a fix coming for this?

**Comment by kossidts** [comment]
The issue is fixed and I have created a PR (https://github.com/jaredwray/keyv/pull/789) which has already been merged. But a new npm package version of [@keyv/mysql](https://www.npmjs.com/package/@keyv/mysql) is not created (yet).

**Comment by jaredwray** [comment]
> The issue is fixed and I have created a PR (#789) which has already been merged. But a new npm package version of [@keyv/mysql](https://www.npmjs.com/package/@keyv/mysql) is not published (yet).

We normally only publish releases on a two week interval with release notes. Can you wait a couple weeks?

**Comment by maxijonson** [comment]
On my end, I don't have an issue with it. After all, it's just a warning. Thanks!

**Comment by jaredwray** [comment]
I went ahead and published. No release notes for a couple weeks but minor fix.
