### ISSUE TITLE
Enable Iterator Functionality in Etcd Storage Adapter

### ISSUE THREAD

**Issue by shcorya** [jaredwray/keyv#841]
**Describe the bug**
The etcd storage package has no iterator function.

**How To Reproduce**
Running with the redis storage package iterates as described in the documentation. Running with the etcd storage package throws `TypeError: keyv.iterator is not a function`.

This code works:
```js
const Keyv = require('keyv');
//const keyv = new Keyv('etcd://localhost:2379');
const keyv = new Keyv ('redis://localhost:6379');
(async () => {

    await keyv.set ('key1', 'value1');
    await keyv.set ('key2', 'value2')
    await keyv.set ('key3', 'value3');

    console.log(keyv.iterator()); // Return: Object [AsyncGenerator] {}
    for await (const [key, value] of keyv.iterator()) {
        console.log(key, value); // Return: key and value
    };

    keyv.disconnect ();

})();
```

Changing to etcd throws the error:
```js
const Keyv = require('keyv');
const keyv = new Keyv('etcd://localhost:2379');
//const keyv = new Keyv ('redis://localhost:6379');
(async () => {

    await keyv.set ('key1', 'value1');
    await keyv.set ('key2', 'value2')
    await keyv.set ('key3', 'value3');

    console.log(keyv.iterator()); // TypeError: keyv.iterator is not a function
    for await (const [key, value] of keyv.iterator()) {
        console.log(key, value);
    };

    keyv.disconnect ();

})();
```

**Comment by jaredwray** [comment]
@shcorya - thanks so much for the issue post on this. Currently etcd does not have iteration enabled at the storage adapter layer. We will keep this open as it looks like we can enable this feature.

**Comment by jaredwray** [comment]
@shcorya - this has been resolved and should be released in the next couple weeks. https://github.com/jaredwray/keyv/pull/857
