### ISSUE TITLE
Redis: add support for KEEPTTL with set

### ISSUE THREAD

**Issue by Aericio** [jaredwray/keyv#858]
**Is your feature request related to a problem? Please describe.**

A throttling system, like 5 usages within 60 seconds.

I could manually adjust the TTL by saving the timestamp in the data, and creating a new key with the difference, but I'd prefer to use the `KEEPTTL` setting on Redis which would keep the existing TTL on the key (unless overwritten).

> Any previous time to live associated with the key is discarded on successful SET operation.

> KEEPTTL -- Retain the time to live associated with the key.

**Describe the solution you'd like**

- Allow `KEEPTTL` option on set operation for the Redis provider.
- Possible usage? `await keyv.set(key, value, { keepttl: true })`
   - So, setting `ttl` would probably look like this also:  `await keyv.set(key, value, { ttl: 100 })`

**References**
- https://redis.github.io/ioredis/classes/Redis.html#set
- https://redis.io/commands/set/

**Comment by jaredwray** [comment]
@Aericio thanks so much for the suggestion. Adding ability for the community to vote on this new feature.

**Comment by christianllv** [comment]
@jaredwray Currently, `keyv.set` supports three parameters: the key, the value, and the optional ttl. Should we modify the set method of Keyv to accept more parameters? I don't think that would be ideal.

Do you have any ideas on how it should work? Perhaps it could be a general parameter of the Keyv instance with the Redis adapter, although I'm not sure if that would be functional in this case.

**Comment by jaredwray** [comment]
Aren't we asking to make it an option in the adapter itself and if set it keeps the ttl if they do not set it?

**Comment by Aericio** [comment]
This should be how you do it in Redis:
> SET key value PX 60
> SET key value KEEPTTL

In Keyv, perhaps we could do something like:
> await keyv.set(key, value, 100)
> await keyv.set(key, value, true)

I suggested the 3rd parameter be an object, however, so that we can allow more customizability in the future. I would like to see `GET`, `NX`, etc options instead of being forced to use `PX` only.

You can see the options here: https://redis.io/commands/set/

**Comment by christianllv** [comment]
@jaredwray but we need to consider that this option needs to be used on the set function, not as a constructor of the adapter class. For this reason, we will need to update the set method to the actual keyv package to pass the param to the adapter.

**Comment by jaredwray** [comment]
@Aericio - I dont know if this would be a good thing to do as we have attempted for a while to keep the storage adapters the same and the set function in line with that where we are passing a number for the ttl.

**Comment by Aericio** [comment]
Ah, that's what you mean by "option in the adapter itself", got it.

**Comment by jaredwray** [comment]
@Aericio and @christianllv - one other option for keyv holistically is to extend the get and set with an additional parameter that is not required called `options` this would allow more complexity to be passed through. I would like to avoid the simplicity that we have with the current set function:

```js
keyv.set(key, value, ttl?, options?)
```
I think it would be better to keep the ttl to a `number` instead of an object as that might cause issues more often. 

thoughts?

**Comment by Aericio** [comment]
I assume, if we don't want `ttl`, we set that as `null`? So: `keyv.set(key, value, null, options)`.

I dislike setting nulls in parameters since it's useless. Is method overloading in typescript a no-go?

**Comment by jaredwray** [comment]
> I assume, if we don't want `ttl`, we set that as `null`? So: `keyv.set(key, value, null, options)`.
> 
> I dislike setting nulls in parameters since it's "useless". Is method overloading in typescript a no-go?

Method overloading is not a great option and keeping all engines the same is key. Going to hold off on this feature set until we get past keyv v5 and then will come back around to it.
