### ISSUE TITLE
Mongo adapter should not store the json as a string

### ISSUE THREAD

**Issue by KevinWh0** [jaredwray/keyv#861]
This issue makes it hard to query the database and search through it with external tools such as Compass. Also the expires field should be moved into the expiresAt field

![image](https://github.com/jaredwray/keyv/assets/45321184/759d80d4-fdf6-40a6-a925-4a11a9dbd66b)

I would like for this to be changed to use actual different fields so that it works with other software/libs/ect that use mongoDB
It should look more like this:

![image](https://github.com/jaredwray/keyv/assets/45321184/05500b43-5023-46c8-8566-e626246ddd10)

**Comment by jaredwray** [comment]
Hi @KevinWh0 - how would this work with typings and different properties as we have seen that many times they are stored in the same cache document collection? 

I dont know if we would do this but happy to see a pull request or have you build this idea out a bit more. Let me know if I can help. Closing for now but happy to re-open if you want to work on this.
