### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by 007jiang7442262** [jaredwray/keyv#901]
![image](https://github.com/jaredwray/keyv/assets/38500885/4a1280b8-7e17-44c7-ae2f-3b5ed414e5a8)

![image](https://github.com/jaredwray/keyv/assets/38500885/4181a5e6-ed24-4b0a-bb15-1635213258e2)

**Comment by jaredwray** [comment]
Hi @007jiang7442262 - I just tested this with one of my packages and it worked great.
