### ISSUE TITLE
`@keyv/redis`: `useRedisSets` option does not take effect when providing `ioredis` instance

### ISSUE THREAD

**Issue by jacksmith15** [jaredwray/keyv#902]
**Describe the bug**

The `useRedisSets` option only takes effect when passing a Redis client as a URI, and does not take effect when passing a `Redis` client directly.

I believe this is because the `useRedisSets` option is set inside [this code branch](https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.ts#L33-L35).

**How To Reproduce (best to provide workable code or tests!)**

```ts
import KeyvRedis from '@keyv/redis';
import { Redis } from 'ioredis';


const REDIS_IP = process.env.REDIS_IP;


const cacheFromInstance: KeyvRedis = new KeyvRedis(
  new Redis({
    host: REDIS_IP,
    port: 6379,
  }),
  { useRedisSets: false },
);

console.log(`Instance useRedisSets: ${cacheFromInstance.opts.useRedisSets}`);


const cacheFromURI: KeyvRedis = new KeyvRedis(
  `redis://${REDIS_IP}:6379`,
  { useRedisSets: false },
);

console.log(`URI useRedisSets: ${cacheFromURI.opts.useRedisSets}`);

```

When executing the above script with `npm exec ts-node reproduce.ts`:

#### Expected output

> Instance useRedisSets: false
> URI useRedisSets: false

#### Actual output

> Instance useRedisSets: true
> URI useRedisSets: false

**Comment by jaredwray** [comment]
@jacksmith15, @kaykdm, and @jawang35 - Thanks for bringing this to our attention. We have a fix and have added unit testing around this. Will be publishing the update today as `v2.7.1`
