### ISSUE TITLE
RedisJSON with Keyv

### ISSUE THREAD

**Issue by markNZed** [jaredwray/keyv#909]
Hi, I've been using Keyv and really like it, thanks. For example, I started out using SQLite and recently moved to Redis with little effort. Also looking forward to V5 with stats and the possibility of running on the browser!

I was wondering about using RedisJSON and whether anyone has gone down that path with Keyv? I guess it would require a custom adaptor. The motivation is to use RediSearch in addition to Keyv.

**Comment by jaredwray** [comment]
Hi @markNZed 👋 - Thanks for the amazing feedback as we work pretty hard to keep this project going. I dont think anybody has done a keyv adapter for RedisJSON but happy to have you take the lead on a third party adapter for it. 

Let me know if you need some help or have questions.

**Comment by markNZed** [comment]
I wonder whether it would be possible to use @keyv/tiered  with Redis backed by MongoDB and get the benefits of Redis as for memory queries and MongoDB for JSON search?

**Comment by jaredwray** [comment]
@markNZed - that is correct with @keyv/tiered you can do two backends with one being your primary and the other your secondary. It will keep them in sync and then you could query MongoDB directly for searching on that collection.

**Comment by markNZed** [comment]
It does seem that if you store JSON objects in mongodb as values within a key-value style in a document, you can query these embedded documents just as you would the top-level fields. It seems like a nice compromise. I understood tiered will be native in V5 so I might wait for that - is there an ETA for V5?

**Comment by jaredwray** [comment]
We hope to have v5 fully live by end of year.
