### ISSUE TITLE
Check the namespace provided to Redis doesn not include ":"

### ISSUE THREAD

**Issue by markNZed** [jaredwray/keyv#924]
**Describe the bug**
I had prefixed a namespace like "something:somethingelse" and the Redis iterator was returning the key and including the namespace. I am not sure if this is a bug (should keyv support `:` in the namespace) or a limitation on Redis and an assertion/error might help.

**How To Reproduce (best to provide workable code or tests!)**

**Comment by jaredwray** [comment]
@markNZed - can you provide a unit test example on how to reproduce?

**Comment by markNZed** [comment]
I can have a go at it. Do you want a PR with a test added to https://github.com/jaredwray/keyv/blob/main/packages/test-suite/src/iterator.ts ?

**Comment by jaredwray** [comment]
That would be great. Let me know if you have any questions.

**Comment by markNZed** [comment]
I like that you have the docker environment to run the tests. I had issues with node/yarn on the server (normally I'm running from inside a docker container on that machine). I wonder whether the yarn/node requirement could be removed so we only need docker and then run the tests inside a docker container. It is not so obvous for an inexperienced dev like me to understand how to modify the test-suite and rerun it in a particular context e.g. redis. Basically I needed to modify the source in packages/test-suit then run yarn build then run yarn test in packages/redis. it is hard to know how much explanation should be provided, I am not familiar with TS or Yarn but I guess most people who would do a PR would b familiar with those tools. https://github.com/jaredwray/keyv/pull/926

**Comment by jaredwray** [comment]
```

	test.serial(
		'iterator() handles : in keys X',
		async t => {
			const keyvStore = store();

			const keyv1 = new Keyv({store: keyvStore, namespace: 'keyv1:testv1'});
			const map1 = new Map(
				Array.from({length: 5})
					.fill(0)
					.map((_x, i) => [String(i) + ":" +	String(i), String(i + 10)]),
			);
			const toResolve = [];
			for (const [key, value] of map1) {
				toResolve.push(keyv1.set(key, value));
			}

			await Promise.all(toResolve);

			t.plan(map1.size);
			for await (const [key, value] of keyv1.iterator()) {
			 	console.log("key", key, "value", value);
				const doesKeyExist = map1.has(key);
				const isValueSame = map1.get(key) === value;
				t.true(doesKeyExist && isValueSame);
			}
		},
	);

};
```

**Comment by jaredwray** [comment]
> I like that you have the docker environment to run the tests. I had issues with node/yarn on the server (normally I'm running from inside a docker container on that machine). I wonder whether the yarn/node requirement could be removed so we only need docker and then run the tests inside a docker container. It is not so obvous for an inexperienced dev like me to understand how to modify the test-suite and rerun it in a particular context e.g. redis. Basically I needed to modify the source in packages/test-suit then run yarn build then run yarn test in packages/redis. it is hard to know how much explanation should be provided, I am not familiar with TS or Yarn but I guess most people who would do a PR would b familiar with those tools. #926

At this time we are keeping the yarn / node requirement as the docker environment is just for testing all the different storage adapters. In most cases what you will see is this sequence in your development terminal:

```bash
yarn 
yarn test:services:start 
yarn test
```
This sequence requires you to have node installed and docker first and then by doing this you will test all the storage adapters in the mono repo.

**Comment by jaredwray** [comment]
Hi @markNZed - I am going to close this out as there are features coming in v5 that help with namespace management.
