### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by markNZed** [jaredwray/keyv#925]
**Describe the bug**
Every time we create a Redis keyv an event is added to monitor Redis errors

https://github.com/jaredwray/keyv/blob/c38b5249341df741188d4036614e92b50a5bd96e/packages/redis/src/index.ts#L39

If we add many keyv this is going to exceed the default max number of listeners (10). 

The warning looks like:

`(node:19415) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit`

I'm unsure if this is a bug - the default limit can be raised. I'm not sure of a good way to address this without adding a lot of complication. I thought I would mention it in case someone does see a solution.

**Comment by jaredwray** [comment]
What we have seen is that people just increase the max listeners when they are using multiple instances. Also, we will be looking to change this in v5 👉 https://github.com/jaredwray/keyv/issues/868
