### ISSUE TITLE
How does the TTL work?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [jaredwray/keyv#963]
Imagine I do have 200 records, each one with a ttl.
I do not perform any further operation in those records, and maybe not even any operation in the KV.

Are the expired records deleted automatically? Is there any scheduler?

If so, is there any way of getting a notification when a key expired and is deleted from memory?

**Comment by jaredwray** [comment]
Hi @MarianoFacundoArch 👋 

It really matters on the storage adapter backend as some have ttl expiry native in the system such as memcache, redis, etc. In other cases we check and expire it in the code and delete it on the storage adapter so it does not come back but it will stay in storage until it is requested.
