### ISSUE TITLE
import or require webpack error.

### ISSUE THREAD

**Issue by Alan-Cn** [jaredwray/keyv#976]
<img width="443" alt="image" src="https://github.com/jaredwray/keyv/assets/34699040/dbae47b9-07e6-44e0-a1e3-778ab7364b90">
<img width="680" alt="image" src="https://github.com/jaredwray/keyv/assets/34699040/e1403cf2-8748-48e6-a500-8b865c930ecf">

This is recognized as an expression. Do you have any ideas about changing it? Error messages are frequent in web applications

**Comment by jaredwray** [comment]
closing this as it will be fixed in v5.

**Comment by Alan-Cn** [comment]
you have any code to fix it ?
 I can fix it by myself.

**Comment by jaredwray** [comment]
@Alan-Cn - the v5 code will not have this functionality and will be resolved with that.
